#!/bin/sh -e

PRETTY_NAME=mandoc
MAJOR=1
MINOR=14
PATCH=6
VERSION=1.14.6

mkdir temporary-builddir
DESTDIR=temporary-builddir

curl --location --remote-name --skip-existing https://mandoc.bsd.lv/snapshots/mandoc-$VERSION.tar.gz

gzip -cd mandoc-$VERSION.tar.gz | tar -x
cd mandoc-$VERSION

patch -p1 < ../mandoc-no-warn.patch

sed -i 's/"more -s"/"less"/g' main.c
sed -i "s/CC=.*/CC=$CC/" configure

cat > configure.local << EOF
PREFIX=/usr
MANDIR=/usr/share/man
LIBDIR=/usr/lib
SBINDIR=/usr/bin
LN="ln -sf"
EOF

./configure

make
make base-install

find "$DESTDIR/usr/bin" -type f -exec strip --strip-unneeded {} \; -exec chmod 755 {} \;

su
chown -R root:root $DESTDIR
cd $DESTDIR
tar -c * | gzip > ../mandoc@$VERSION.tar.gz
exit
