#!/bin/sh -e

DEPENDENCIES="zlib"
INFO="Suite of tools compiling mdoc and man"
PRETTY_NAME="mandoc"
SOURCES="https://mandoc.bsd.lv/snapshots/mandoc-$VERSION.tar.gz"
SOURCES="$SOURCES patches/mandoc-no-warn.patch"
MAJOR="1"
MINOR="14"
PATCH="6"
VERSION="$MAJOR.$MINOR.$PATCH"
