#!/bin/sh -e

tar -xf libxkbcommon-$VERSION.tar.xz
cd libxkbcommon-$VERSION

muon setup \
	-Dprefix=/usr \
	-Dlibdir=/usr/lib \
	-Dlibexecdir=/usr/lib \
	-Dbuildtype=release \
	-Ddefault_library=both \
	-Denable-docs=false \
	-Denable-wayland=true \
	-Denable-x11=false \
	-Denable-xkbregistry=false \
	build

muon -C build samu
muon -C build install -d "$DESTDIR"

rm -rf "$DESTDIR/usr/share/bash-completion"

find "$DESTDIR/usr/lib" -type f -name '*.a'   -exec strip --strip-unneeded {} \;
find "$DESTDIR/usr/lib" -type f -name '*.so*' -exec strip --strip-unneeded {} \;
find "$DESTDIR/usr/lib/xkbcommon" -type f     -exec strip --strip-unneeded {} \;
strip --strip-unneeded "$DESTDIR/usr/bin/xkbcli"
