#!/bin/sh -e

xz -cd e2fsprogs-$VERSION.tar.xz | tar -x
cd e2fsprogs-$VERSION

./configure \
	--prefix=/usr \
	--sbindir=/usr/bin \
	--sysconfdir=/etc \
	--enable-symlink-install \
	--disable-libuuid \
	--disable-libblkid \
	--disable-nls \
	--disable-uuidd \
	--disable-fsck \
	--disable-elf-shlibs \
	--disable-tls \
	--disable-lto \
	--disable-fuse2fs \
	--disable-e2initrd-helper \
	--with-pthread \
	--without-systemd-unit-dir \
	--without-udev-rules-dir
	
make
make DESTDIR="$DESTDIR" install-strip

rmdir "$DESTDIR/usr/share/info"

su
chown -R root:root $DESTDIR
cd $DESTDIR
tar -c * | gzip > ../e2fsprogs@$VERSION.tar.gz
exit
