#!/bin/sh -e

DEPENDENCIES="pkgconf"
INFO=""
PRETTY_NAME="e2fsprogs"
SOURCES="https://kernel.org/pub/linux/kernel/people/tytso/e2fsprogs/v$VERSION/e2fsprogs-$VERSION.tar.xz"
MAJOR="1"
MINOR="47"
PATCH="1"
VERSION="$MAJOR.$MINOR.$PATCH"
