#!/bin/sh -e

tar -xf libglvnd-v$VERSION.tar.gz
cd libglvnd-v$VERSION

muon setup -Dprefix=/usr -Dbuildtype=release build

muon -C build samu
muon -C build install -d "$DESTDIR"

find "$DESTDIR/usr/lib" -type f -name '*.a'   -exec strip --strip-unneeded {} \;
find "$DESTDIR/usr/lib" -type f -name '*.so*' -exec strip --strip-unneeded {} \;
find $DESTDIR -type f -name '*.la' -delete
