#!/bin/sh -e

PRETTY_NAME=curl
MAJOR=8
MINOR=12
PATCH=1
VERSION=8.12.1

mkdir temporary-builddir
DESTDIR=temporary-builddir

curl --location --remote-name --skip-existing https://curl.haxx.se/download/curl-$VERSION.tar.xz

xz -cd curl-$VERSION.tar.xz | tar -x
cd curl-$VERSION

./configure \
	--prefix=/usr \
	--enable-ipv6 \
	--enable-unix-sockets \
	--enable-symbol-hiding \
	--disable-manual \
	--disable-docs \
	--disable-ldap \
	--disable-ares \
	--with-openssl \
	--with-pic \
	--with-ca-fallback \
	--without-librtmp \
	--without-libpsl \
	--without-libidn2 \
	--without-brotli \
	--without-zstd

make
make DESTDIR="$DESTDIR" install-strip

rm -rf "$DESTDIR/usr/share"

find $DESTDIR -type f -name '*.la' -delete

su
chown -R root:root $DESTDIR
cd $DESTDIR
tar -c * | gzip > ../curl@$VERSION.tar.gz
exit
