#!/bin/sh -e

xz -cd curl-$VERSION.tar.xz | tar -x
cd curl-$VERSION

./configure \
	--prefix=/usr \
	--enable-ipv6 \
	--enable-unix-sockets \
	--enable-symbol-hiding \
	--disable-manual \
	--disable-docs \
	--disable-ldap \
	--disable-ares \
	--with-openssl \
	--with-pic \
	--with-ca-fallback \
	--without-librtmp \
	--without-libpsl \
	--without-libidn2 \
	--without-brotli \
	--without-zstd

make
make DESTDIR="$DESTDIR" install-strip

rm -rf "$DESTDIR/usr/share/aclocal"

find $DESTDIR -type f -name '*.la' -delete

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > curl@$VERSION.tar.gz
exit
