#!/bin/sh -e

DEPENDENCIES="libressl zlib"
INFO="A Client that groks URLs"
PRETTY_NAME="curl"
SOURCES="https://curl.haxx.se/download/curl-$VERSION.tar.xz"
MAJOR="8"
MINOR="12"
PATCH="1"
VERSION="$MAJOR.$MINOR.$PATCH"
