#!/bin/sh -e

PRETTY_NAME=libxkbcommon
MAJOR=1
MINOR=7
PATCH=0
VERSION=1.7.0

mkdir temporary-builddir
DESTDIR=temporary-builddir

curl --location --remote-name --skip-existing https://xkbcommon.org/download/libxkbcommon-$VERSION.tar.xz

xz -cd libxkbcommon-$VERSION.tar.xz | tar -x
cd libxkbcommon-$VERSION

meson setup \
	-Dprefix=/usr \
	-Dlibdir=/usr/lib \
	-Dlibexecdir=/usr/lib \
	-Dbuildtype=release \
	-Ddefault_library=both \
	-Denable-docs=false \
	-Denable-wayland=true \
	-Denable-x11=false \
	-Denable-xkbregistry=false \
	build

meson -C build compile
meson -C build install -d "$DESTDIR"

rm -rf "$DESTDIR/usr/share/bash-completion"

find "$DESTDIR/usr/lib" -type f -name '*.a'   -exec strip --strip-unneeded {} \;
find "$DESTDIR/usr/lib" -type f -name '*.so*' -exec strip --strip-unneeded {} \;
find "$DESTDIR/usr/lib/xkbcommon" -type f     -exec strip --strip-unneeded {} \;
strip --strip-unneeded "$DESTDIR/usr/bin/xkbcli"

su
chown -R root:root $DESTDIR
cd $DESTDIR
tar -c * | gzip > ../libxkbcommon@$VERSION.tar.gz
exit
