#!/bin/sh -e

xz -cd libxkbcommon-$VERSION.tar.xz | tar -x
cd libxkbcommon-$VERSION

meson setup \
	-Dprefix=/usr \
	-Dlibdir=/usr/lib \
	-Dlibexecdir=/usr/lib \
	-Dbuildtype=release \
	-Ddefault_library=both \
	-Denable-docs=false \
	-Denable-wayland=true \
	-Denable-x11=false \
	-Denable-xkbregistry=false \
	build

meson -C build compile
meson -C build install -d "$DESTDIR"

rm -rf "$DESTDIR/usr/share/bash-completion"

find "$DESTDIR/usr/lib" -type f -name '*.a'   -exec strip --strip-unneeded {} \;
find "$DESTDIR/usr/lib" -type f -name '*.so*' -exec strip --strip-unneeded {} \;
find "$DESTDIR/usr/lib/xkbcommon" -type f     -exec strip --strip-unneeded {} \;
strip --strip-unneeded "$DESTDIR/usr/bin/xkbcli"

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > libxkbcommon@$VERSION.tar.gz
exit
