#!/bin/sh -e

DEPENDENCIES="bison compose-tables meson pkgconf wayland wayland-protocols xkeyboard-config"
INFO="keymap handling library for toolkits and window systems"
PRETTY_NAME="libxkbcommon"
SOURCES="https://xkbcommon.org/download/libxkbcommon-$VERSION.tar.xz"
MAJOR="1"
MINOR="7"
PATCH="0"
VERSION="$MAJOR.$MINOR.$PATCH"
