#!/bin/sh -e

gzip -cd v$VERSION.tar.gz | tar -x
cd dhcpcd-$VERSION

# To do: enable priviledge separation
./configure \
	--dbdir=/var/lib/dhcpcd \
	--prefix=/usr \
	--sbindir=/usr/bin \
	--sysconfdir=/etc \
	--rundir=/run \
	--libexecdir=/usr/lib/dhcpcd \
	--disable-privsep \
	--without-udev \
	--without-openssl

make
make DESTDIR="$DESTDIR" BINMODE=755 install

install -Dm755 ../dhcpcd.run "$DESTDIR/etc/sv/dhcpcd/run"
ln -sf /run/runit/supervise.dhcpcd "$DESTDIR/etc/sv/dhcpcd/supervise"

strip --strip-unneeded "$DESTDIR/usr/bin/dhcpcd"

su
chown -R root:root $DESTDIR
cd $DESTDIR
tar -c * | gzip > ../dhcpcd@$VERSION.tar.gz
exit
