#!/bin/sh -e

DEPENDENCIES="linux-headers"
INFO="A fully featured, yet light weight RFC2131 compliant DHCP client"
PRETTY_NAME="dhcpcd"
SOURCES="https://github.com/NetworkConfiguration/dhcpcd/archive/refs/tags/v$VERSION.tar.gz"
SOURCES="$SOURCES files/dhcpcd.run"
MAJOR="10"
MINOR="0"
PATCH="8"
VERSION="$MAJOR.$MINOR.$PATCH"
