#!/bin/sh -e

tar -xf libinput-$VERSION.tar.gz
cd libinput-$VERSION

muon setup \
	-Dprefix=/usr \
	-Dsysconfdir=/etc \
	-Dmandir=/usr/share/man \
	-Dlibexecdir=/usr/lib \
	-Ddefault_library=both \
	-Dbuildtype=release \
	-Ddebug-gui=false \
	-Ddocumentation=false \
	-Dtests=false \
	-Dlibwacom=false \
	-Dzshcompletiondir=no \
	build

muon -C build samu
muon -C build install -d "$DESTDIR"

strip --strip-unneeded "$DESTDIR/usr/bin/libinput"
find "$DESTDIR/usr/lib" -type f -name '*.a'   -exec strip --strip-unneeded {} \;
find "$DESTDIR/usr/lib" -type f -name '*.so*' -exec strip --strip-unneeded {} \;
