#!/bin/sh -e

gzip -cd v$VERSION.tar.gz | tar -x

install -Dm644 -t "$DESTDIR/usr/share/lua/cassowary" cassowary.lua-$VERSION/cassowary/init.lua

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > cassowary@$VERSION.tar.gz
exit
