#!/bin/sh -e

DEPENDENCIES="lua penlight"
INFO=""
PRETTY_NAME="cassowary"
SOURCES="https://github.com/sile-typesetter/cassowary.lua/archive/refs/tags/v$VERSION.tar.gz"
MAJOR="2"
MINOR="3"
PATCH="2"
VERSION="$MAJOR.$MINOR.$PATCH"
