#!/bin/sh -e

PRETTY_NAME=binutils
MAJOR=2
MINOR=44
PATCH=
VERSION=2.44

mkdir temporary-builddir
DESTDIR=temporary-builddir

curl --location --remote-name --skip-existing https://ftp.gnu.org/gnu/binutils/binutils-$VERSION.tar.xz

tar -xf binutils-$VERSION.tar.xz
cd binutils-$VERSION

./configure \
	--prefix=/usr \
	--with-lib-path=/usr/lib \
	--enable-deterministic-archives \
	--enable-ld=default \
	--enable-plugins \
	--disable-jansson \
	--disable-gold \
	--disable-lto \
	--disable-multilib \
	--disable-werror \
	--disable-gdb \
	--disable-nls \
	--disable-readline \
	--disable-gprof \
	--disable-gprofng \
	--with-mmap \
	--with-system-zlib \
	--without-zstd

make configure-host
make tooldir=/usr
make tooldir=/usr DESTDIR="$DESTDIR" install-strip

rm -rf "$DESTDIR/usr/share/info"
find $DESTDIR -type f -name '*.la' -delete

su
chown -R root:root $DESTDIR
tar -c -C $DESTDIR . | gzip > ../binutils@$VERSION.tar.gz
exit
