#!/bin/sh -e

gzip -cd v$VERSION.tar.gz | tar -x
cd ccore-$VERSION/src/openbsd/patch
cp ../compat.h .

$CC -c *.c
$CC -static *.o -o patch

install -Dm755 patch "$DESTDIR/usr/bin/patch"
install -Dm644 patch "$DESTDIR/usr/share/man/man1/patch.1"

strip --strip-unneeded "$DESTDIR/usr/bin/patch"

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > patch@$VERSION.tar.gz
exit
