#!/bin/sh -e

gzip -d v$VERSION.tar.gz | tar -x
cd ccore-$VERSION/src/openbsd/patch
cp ../compat.h .

$CC -c *.c
$CC -static *.o -o patch

install -Dm755 -t "$DESTDIR/usr/bin" patch
install -Dm644 -t "$DESTDIR/usr/share/man/man1" patch.1

strip --strip-unneeded "$DESTDIR/usr/bin/patch"
