#!/bin/sh -e

DEPENDENCIES=""
INFO="Utility to apply diffs to files"
PRETTY_NAME="patch"
SOURCES="https://github.com/eltanin-os/ccore/archive/refs/tags/v$VERSION.tar.gz"
MAJOR="0"
MINOR="1"
PATCH="0"
VERSION="$MAJOR.$MINOR.$PATCH"
