#!/bin/sh -e

gzip -cd v$VERSION.tar.gz | tar -x
cd hwdata-$VERSION

./configure \
	--prefix=/usr \
	--libdir=/usr/lib \
	--datadir=/usr/lib \
	--disable-blacklist

make
make install

su
chown -R root:root $DESTDIR
exit
