#!/bin/sh -e

PRETTY_NAME=hwdata
MAJOR=0
MINOR=382
PATCH=
VERSION=0.382

mkdir temporary-builddir
DESTDIR=temporary-builddir

curl --location --remote-name --skip-existing https://github.com/vcrhonek/hwdata/archive/refs/tags/v.tar.gz
gzip -cd v$VERSION.tar.gz | tar -x
cd hwdata-$VERSION

./configure \
	--prefix=/usr \
	--libdir=/usr/lib \
	--datadir=/usr/lib \
	--disable-blacklist

make
make install

su
chown -R root:root $DESTDIR
tar -c -C $DESTDIR . | gzip > ../hwdata@$VERSION.tar.gz
exit
