#!/bin/sh -e

cd sbase.git

patch -p1 < ../install-add-GNU-s-extension.patch

make \
	PREFIX=/usr \
	CFLAGS="$CFLAGS -static" \
	LDFLAGS="$LDFLAGS -static"

make \
	PREFIX=/usr \
	CFLAGS="$CFLAGS -static" \
	LDFLAGS="$LDFLAGS -static" \
	DESTDIR="$DESTDIR" \
	install

install -Dm755 ../cron.run       "$DESTDIR/etc/sv/cron/run"
ln -sf /run/runit/supervise.cron "$DESTDIR/etc/sv/cron/supervise"

mv "$DESTDIR/usr/bin/xinstall"              "$DESTDIR/usr/bin/install"
mv "$DESTDIR/usr/share/man/man1/xinstall.1" "$DESTDIR/usr/share/man/man1/install.1"

# strings and xargs already provided

rm "$DESTDIR/usr/bin/strings"
rm "$DESTDIR/usr/bin/xargs"
rm "$DESTDIR/usr/share/man/man1/strings.1"
rm "$DESTDIR/usr/share/man/man1/xargs.1"

# tar, find, grep, and sed are (sadly) too strict to be usable

rm "$DESTDIR/usr/bin/tar"
rm "$DESTDIR/usr/bin/find"
rm "$DESTDIR/usr/bin/grep"
rm "$DESTDIR/usr/bin/sed"
rm "$DESTDIR/usr/share/man/man1/tar.1"
rm "$DESTDIR/usr/share/man/man1/find.1"
rm "$DESTDIR/usr/share/man/man1/grep.1"
rm "$DESTDIR/usr/share/man/man1/sed.1"

find "$DESTDIR/usr/bin" -type f -exec strip --strip-unneeded {} \;
