#!/bin/sh -e

PRETTY_NAME=seatd
MAJOR=0
MINOR=8
PATCH=0
VERSION=0.8.0

mkdir temporary-builddir
DESTDIR="$PWD/temporary-builddir"

curl --location --remote-name --skip-existing https://git.sr.ht/~kennylevinsen/seatd/archive/.tar.gz
gzip -cd $VERSION.tar.gz | tar -x
cd seatd-$VERSION

meson setup \
    -Dprefix=/usr \
    -Ddefault_library=both \
    -Dbuildtype=release \
    build

meson -C build compile
meson -C build install -d "$DESTDIR"

install -Dm755 ../seatd.run "$DESTDIR/etc/sv/seatd/run"
ln -sf /run/runit/supervise.seatd "$DESTDIR/etc/sv/seatd/supervise"

find "$DESTDIR/usr/lib" -type f -name '*.a'   -exec strip --strip-unneeded {} \;
find "$DESTDIR/usr/lib" -type f -name '*.so*' -exec strip --strip-unneeded {} \;

su
chown -R root:root $DESTDIR
tar -zcC $DESTDIR . | gzip > ../seatd@$VERSION.tar.gz
exit
