#!/bin/sh -e

DEPENDENCIES="meson"
INFO="Minimal seat management daemon and universal library"
PRETTY_NAME="seatd"
SOURCES="https://git.sr.ht/~kennylevinsen/seatd/archive/$VERSION.tar.gz"
SOURCES="$SOURCES files/seatd.run"
MAJOR="0"
MINOR="8"
PATCH="0"
VERSION="$MAJOR.$MINOR.$PATCH"
