#!/bin/sh -e

PRETTY_NAME=linux
MAJOR=6
MINOR=15
PATCH=1
VERSION=6.15.1

mkdir temporary-builddir
DESTDIR="$PWD/temporary-builddir"

curl --location --remote-name --skip-existing https://mirrors.edge.kernel.org/pub/linux/kernel/v$MAJOR.x/linux-$VERSION.tar.xz

xz -cd linux-$VERSION.tar.xz | tar -x
cd linux-$VERSION

make HOSTCC="$CC" headers

find usr/include -name \*.h -type f -exec install -Dm644 {} $DESTDIR/{} \;

doas chown -R root:root $DESTDIR
doas sh -c "tar -zcC $DESTDIR . | gzip > ../linux-headers@$VERSION.tar.gz"
