#!/bin/sh -e

xz -cd linux-$VERSION.tar.xz | tar -x
cd linux-$VERSION

make HOSTCC="$CC" headers

find usr/include -name \*.h -type f -exec install -Dm644 {} $DESTDIR/{} \;

su
chown -R root:root $DESTDIR
cd $DESTDIR
tar -c * | gzip > ../linux-headers@$VERSION.tar.gz
exit
