#!/bin/sh -e

DEPENDENCIES=""
INFO="Linux headers"
PRETTY_NAME="linux-headers"
SOURCES="https://mirrors.edge.kernel.org/pub/linux/kernel/v$MAJOR.x/linux-$VERSION.tar.xz"
MAJOR="6"
MINOR="6"
PATCH="7"
VERSION="$MAJOR.$MINOR.$PATCH"
