#!/bin/sh -e

gzip -cd toybox-$VERSION.tar.gz | tar -x
cd toybox-$VERSION

make defconfig

CFLAGS="$CFLAGS -static" LDFLAGS="$LDFLAGS -static" make find
install -Dm755 find "$DESTDIR/usr/bin/find"
strip --strip-unneeded "$DESTDIR/usr/bin/find"

CFLAGS="$CFLAGS -static" LDFLAGS="$LDFLAGS -static" make xargs
install -Dm755 xargs "$DESTDIR/usr/bin/xargs"
strip --strip-unneeded "$DESTDIR/usr/bin/xargs"

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > findutils@$VERSION.tar.gz
exit
