#!/bin/sh -e

xz -d findutils-$VERSION.tar.xz | tar -x
cd findutils-$VERSION

./configure --prefix=/usr

make
make DESTDIR="$DESTDIR" install-strip

rm -rf "$DESTDIR/usr/share/info"
rm -rf "$DESTDIR/usr/share/locale"
