#!/bin/sh -e

xz -cd findutils-$VERSION.tar.xz | tar -x
cd findutils-$VERSION

./configure --prefix=/usr

make
make DESTDIR="$DESTDIR" install-strip

rm -rf "$DESTDIR/usr/share/info"
rm -rf "$DESTDIR/usr/share/locale"

su
chown -R root:root $DESTDIR
exit
