#!/bin/sh -e

DEPENDENCIES=""
INFO="Find files"
PRETTY_NAME="findutils"
SOURCES="https://landley.net/toybox/downloads/toybox-$VERSION.tar.gz"
MAJOR="0"
MINOR="8"
PATCH="12"
VERSION="$MAJOR.$MINOR.$PATCH"
