#!/bin/sh -e

gzip -cd v$VERSION.tar.gz | tar -x

install -Dm644 -t "$DESTDIR/usr/share/lua" loadkit-$VERSION/loadkit.lua

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > loadkit@$VERSION.tar.gz
exit
