#!/bin/sh -e

DEPENDENCIES="lua"
INFO=""
PRETTY_NAME="loadkit"
SOURCES="https://github.com/leafo/loadkit/archive/refs/tags/v$VERSION.tar.gz"
MAJOR="1"
MINOR="1"
PATCH="0"
VERSION="$MAJOR.$MINOR.$PATCH"
