#!/bin/sh -e

tar -xf v$VERSION.tar.gz
cd mdevd-$VERSION

./configure \
	--prefix=/usr \
	--enable-static-libc

make
make DESTDIR="$DESTDIR" install-strip

install -Dm644 ../mdevd.conf "$DESTDIR/etc/mdevd.conf"
install -Dm755 ../mdevd.run  "$DESTDIR/etc/sv/mdevd/run"
ln -sf /run/runit/supervise.mdevd "$DESTDIR/etc/sv/mdevd/supervise"

rm -rf "$DESTDIR/usr/include"
