#!/bin/sh -e

gzip -d libffi-$VERSION.tar.gz | tar -x
cd libffi-$VERSION

./configure \
    --prefix=/usr \
    --disable-exec-static-tramp \
    --with-pic

make
make install-strip

rm -rf "$DESTDIR/usr/share"
find $DESTDIR -type f -name '*.la' -delete
