#!/bin/sh -e

PRETTY_NAME=libffi
MAJOR=3
MINOR=4
PATCH=6
VERSION=3.4.6

mkdir temporary-builddir
DESTDIR=temporary-builddir

curl --location --remote-name --skip-existing https://github.com/libffi/libffi/releases/download/v/libffi-$VERSION.tar.gz

gzip -cd libffi-$VERSION.tar.gz | tar -x
cd libffi-$VERSION

./configure \
    --prefix=/usr \
    --disable-exec-static-tramp \
    --with-pic

make
make install-strip

rm -rf "$DESTDIR/usr/share"
find $DESTDIR -type f -name '*.la' -delete

su
chown -R root:root $DESTDIR
cd $DESTDIR
tar -c * | gzip > ../libffi@$VERSION.tar.gz
exit
