#!/bin/sh -e

DEPENDENCIES=""
INFO="a portable, high level programming interface to various calling conventions"
PRETTY_NAME="libffi"
SOURCES="https://github.com/libffi/libffi/releases/download/v$VERSION/libffi-$VERSION.tar.gz"
MAJOR="3"
MINOR="4"
PATCH="6"
VERSION="$MAJOR.$MINOR.$PATCH"
