#!/bin/sh -e

tar -xf v$VERSION.tar.gz
cd dhcpcd-$VERSION

./configure \
	--prefix=/usr \
	--sbindir=/usr/bin \
	--sysconfdir=/etc \
	--rundir=/run \
	--libexecdir=/usr/lib/dhcpcd \
	--without-udev

make
make DESTDIR="$DESTDIR" BINMODE=755 install

install -Dm755 ../dhcpcd.run "$DESTDIR/etc/sv/dhcpcd/run"
ln -sf /run/runit/supervise.dhcpcd "$DESTDIR/etc/sv/dhcpcd/supervise"

rm -rf "$DESTDIR/var"
