#!/bin/sh -e

gzip -cd v$VERSION.tar.gz | tar -x
cd ccore-$VERSION/src/openbsd/diff
cp ../compat.h .

$CC -c *.c
$CC -static *.o -o diff

install -Dm755 diff "$DESTDIR/usr/bin/diff"
install -Dm644 diff.1 "$DESTDIR/usr/share/man/man1/diff.1"

strip --strip-unneeded "$DESTDIR/usr/bin/diff"

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > diff@$VERSION.tar.gz
exit
