#!/bin/sh -e

tar -xf v$PKGVER.tar.gz
cd netbsd-curses-$PKGVER

make PREFIX=/usr all
make PREFIX=/usr DESTDIR="$DESTDIR" install

ln -sf libterminfo.so "$DESTDIR/usr/lib/libtinfo.so"

# Remove duplicate
rm "$DESTDIR/usr/bin/clear"
rm "$DESTDIR/usr/share/man/man1/clear.1"

rm -rf "$DESTDIR/usr/share/man/man3"

find "$DESTDIR/usr/bin"       -type f -exec strip --strip-unneeded {} \;
find "$DESTDIR" -name '*.a'   -type f -exec strip --strip-unneeded {} \;
find "$DESTDIR" -name '*.so*' -type f -exec strip --strip-unneeded {} \;
