#!/bin/sh -e

PRETTY_NAME=init-scripts
MAJOR=
MINOR=
PATCH=
VERSION=git

mkdir temporary-builddir
DESTDIR="$PWD/temporary-builddir"

git clone https://codeberg.org/kiss-community/init.git
cd init-scripts.git

patch -p1 < ../support-toybox.patch

sed -i 's|:-KISS||g' lib/init/rc.boot
sed -i 's| to KISS||g' lib/init/rc.boot
sed -i 's|=>|!!|g' lib/init/rc.lib
 
install -Dm755 lib/init/rc.lib      "$DESTDIR/usr/lib/init/rc.lib"
install -Dm755 lib/init/rc.boot     "$DESTDIR/usr/lib/init/rc.boot"
install -Dm755 lib/init/rc.shutdown "$DESTDIR/usr/lib/init/rc.shutdown"

install -Dm644 etc/rc.conf "$DESTDIR/etc/rc.conf"

$CC -static -o kpow bin/kpow.c
install -Dm755 kpow    "$DESTDIR/usr/bin/kpow"
strip --strip-unneeded "$DESTDIR/usr/bin/kpow"

su
chown -R root:root $DESTDIR
tar -zcC $DESTDIR . | gzip > ../init-scripts@$VERSION.tar.gz
exit
