#!/bin/sh -e

cd init-scripts.git
 
patch -p1 < ../unkissify.patch
 
$CC -o kpow bin/kpow.c -static
 
install -Dm755 lib/init/rc.lib       "$DESTDIR/usr/lib/init/rc.lib"
install -Dm755 lib/init/rc.boot      "$DESTDIR/usr/lib/init/rc.boot"
install -Dm755 lib/init/rc.shutdown  "$DESTDIR/usr/lib/init/rc.shutdown"
install -Dm755 kpow                  "$DESTDIR/usr/bin/kpow"

install -Dm644 ../inittab "$DESTDIR/etc/inittab"

strip --strip-unneeded "$DESTDIR/usr/bin/kpow"

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > init-scripts@$VERSION.tar.gz
exit
