#!/bin/sh -e

DEPENDENCIES=""
INFO="init-agnostic init scripts from KISS linux"
PRETTY_NAME="init-scripts"
SOURCES="https://codeberg.org/kiss-community/init.git"
SOURCES="$SOURCES patches/support-ubase.patch"
VERSION="git"
