#!/bin/sh -e

PRETTY_NAME=libinput
MAJOR=1
MINOR=25
PATCH=0
VERSION=1.25.0

mkdir temporary-builddir
DESTDIR=temporary-builddir

curl --location --remote-name --skip-existing https://gitlab.freedesktop.org/libinput/libinput/-/archive//libinput-$VERSION.tar.gz

gzip -cd libinput-$VERSION.tar.gz | tar -x
cd libinput-$VERSION

meson setup \
	-Dprefix=/usr \
	-Dsysconfdir=/etc \
	-Dmandir=/usr/share/man \
	-Dlibexecdir=/usr/lib \
	-Ddefault_library=both \
	-Dbuildtype=release \
	-Ddebug-gui=false \
	-Ddocumentation=false \
	-Dtests=false \
	-Dlibwacom=false \
	-Dzshcompletiondir=no \
	build

meson -C build compile
meson -C build install -d "$DESTDIR"

strip --strip-unneeded "$DESTDIR/usr/bin/libinput"
find "$DESTDIR/usr/lib" -type f -name '*.a'   -exec strip --strip-unneeded {} \;
find "$DESTDIR/usr/lib" -type f -name '*.so*' -exec strip --strip-unneeded {} \;

su
chown -R root:root $DESTDIR
cd $DESTDIR
tar -c * | gzip > ../libinput@$VERSION.tar.gz
exit
