#!/bin/sh -e

PRETTY_NAME=libinput
MAJOR=1
MINOR=29
PATCH=2
VERSION=1.29.2

if [ ! -f $0 ]; then return; fi

mkdir temporary-distdir
DESTDIR="$PWD/temporary-distdir"

curl --location --remote-name --skip-existing https://gitlab.freedesktop.org/libinput/libinput/-/archive/$VERSION/libinput-$VERSION.tar.gz

gzip -cd libinput-$VERSION.tar.gz | tar -x
cd libinput-$VERSION

# Libinput has no support for static linking, which is why the default_library
# directive doesn't actually do anything. It's there just in case things change
# in the future

# TODO: libwacom has to be toggled on and off explicitly. Wouldn't it make
# much more sense to use automatic discovery?

muon setup \
	-D prefix=/usr \
	-D sysconfdir=/etc \
	-D mandir=/usr/share/man \
	-D libexecdir=/usr/lib \
	-D default_library=both \
	-D buildtype=release \
	-D debug-gui=false \
	-D documentation=false \
	-D tests=false \
	-D zshcompletiondir=no \
	-D libwacom=false \
	build

ninja -C build
muon -C build install -d "$DESTDIR"

strip --strip-unneeded "$DESTDIR/usr/bin/libinput"
find "$DESTDIR/usr/lib" -type f -name '*.a'   -exec strip --strip-unneeded {} \;
find "$DESTDIR/usr/lib" -type f -name '*.so*' -exec strip --strip-unneeded {} \;

# TODO: Since we use libudev-zero, can't we just remove installed udev rules? Should we?

doas chown -R root:root $DESTDIR
doas sh -c "tar -zcC $DESTDIR . | gzip > ../libinput@$VERSION.tar.gz"
CALLER_UID=$(id -un)
CALLER_GID=$(id -gn)
doas chown -R $CALLER_UID:$CALLER_GID $DESTDIR
