#!/bin/sh -e

DEPENDENCIES="libevdev libudev-zero linux-headers mtdev meson pkgconf"
INFO="Library to handle input devices in Wayland"
PRETTY_NAME="libinput"
SOURCES="https://gitlab.freedesktop.org/libinput/libinput/-/archive/$VERSION/libinput-$VERSION.tar.gz"
MAJOR="1"
MINOR="25"
PATCH="0"
VERSION="$MAJOR.$MINOR.$PATCH"
