#!/bin/sh -e

tar -xf gdb-$VERSION.tar.xz
cd gdb-$VERSION

./configure \
	--prefix=/usr \
	--without-installed-readline \
	--disable-nls

make
make -C gdb DESTDIR="$DESTDIR" install-strip
make -C gdbserver DESTDIR="$DESTDIR" install-strip

rm -rf "$DESTDIR/usr/share/info"
