#!/bin/sh -e

PRETTY_NAME=gdb
MAJOR=14
MINOR=1
PATCH=
VERSION=14.1

mkdir temporary-builddir
DESTDIR=temporary-builddir

curl --location --remote-name --skip-existing https://ftp.gnu.org/gnu/gdb/gdb-$VERSION.tar.xz

xz -cd gdb-$VERSION.tar.xz | tar -x
cd gdb-$VERSION

./configure \
	--prefix=/usr \
	--without-installed-readline \
	--disable-nls

make
make -C gdb DESTDIR="$DESTDIR" install-strip
make -C gdbserver DESTDIR="$DESTDIR" install-strip

rm -rf "$DESTDIR/usr/share/info"

su
chown -R root:root $DESTDIR
cd $DESTDIR
tar -c * | gzip > ../gdb@$VERSION.tar.gz
exit
