#!/bin/sh -e

tar -xf wlroots-$VERSION.tar.gz
cd wlroots-$VERSION

muon setup \
	-Dprefix=/usr \
	-Ddefault_library=both \
	-Dexamples=false \
	-Dbackends=libinput,drm \
	-Dxcb-errors=disabled \
	-Drenderers=gles2 \
	build

muon -C build samu
muon -C build install -d "$DESTDIR"

find "$DESTDIR/usr/lib" -type f -name '*.a'   -exec strip --strip-unneeded {} \;
find "$DESTDIR/usr/lib" -type f -name '*.so*' -exec strip --strip-unneeded {} \;
