#!/bin/sh -e

PRETTY_NAME=ca-certificates
MAJOR=2024
MINOR=12
PATCH=31
VERSION=2024-12-31

mkdir temporary-builddir
DESTDIR=temporary-builddir

curl --location --remote-name --skip-existing https://curl.se/ca/cacert-.pem
install -Dm644 cacert-$VERSION.pem "$DESTDIR/etc/ssl/cert.pem"

su
chown -R root:root $DESTDIR
tar -c -C $DESTDIR . | gzip > ../ca-certificates@$VERSION.tar.gz
exit
