#!/bin/sh -e

PRETTY_NAME=ca-certificates
MAJOR=2025
MINOR=11
PATCH=04
VERSION=2025-11-04

mkdir temporary-distdir
DESTDIR="$PWD/temporary-distdir"

curl --location --remote-name --skip-existing https://curl.se/ca/cacert-$VERSION.pem

install -Dm644 cacert-$VERSION.pem "$DESTDIR/etc/ssl/cert.pem"

doas chown -R root:root $DESTDIR
doas sh -c "tar -zcC $DESTDIR . | gzip > ca-certificates@$VERSION.tar.gz"
CALLER_UID=$(id -un)
CALLER_GID=$(id -gn)
doas chown -R $CALLER_UID:$CALLER_GID $DESTDIR
