#!/bin/sh -e

tar -xf wayland-protocols-$VERSION.tar.xz
cd wayland-protocols-$VERSION

meson setup \
	-Dprefix=/usr \
	-Ddatadir=lib \
	-Dbuildtype=release \
	-Dtests=false \
	build

meson -C build compile
meson -C build install -d "$DESTDIR"
