#!/bin/sh -e

gzip -cd libglvnd-v$VERSION.tar.gz | tar -x
cd libglvnd-v$VERSION

meson setup -Dprefix=/usr -Dbuildtype=release build

meson -C build compile
meson -C build install -d "$DESTDIR"

find "$DESTDIR/usr/lib" -type f -name '*.a'   -exec strip --strip-unneeded {} \;
find "$DESTDIR/usr/lib" -type f -name '*.so*' -exec strip --strip-unneeded {} \;

su
chown -R root:root $DESTDIR
exit
