#!/bin/sh -e

PRETTY_NAME=libglvnd
MAJOR=1
MINOR=7
PATCH=0
VERSION=1.7.0

mkdir temporary-builddir
DESTDIR=temporary-builddir

curl --location --remote-name --skip-existing https://gitlab.freedesktop.org/glvnd/libglvnd/-/archive/v/libglvnd-v.tar.gz
gzip -cd libglvnd-v$VERSION.tar.gz | tar -x
cd libglvnd-v$VERSION

meson setup -Dprefix=/usr -Dbuildtype=release build

meson -C build compile
meson -C build install -d "$DESTDIR"

find "$DESTDIR/usr/lib" -type f -name '*.a'   -exec strip --strip-unneeded {} \;
find "$DESTDIR/usr/lib" -type f -name '*.so*' -exec strip --strip-unneeded {} \;

su
chown -R root:root $DESTDIR
tar -c -C $DESTDIR . | gzip > ../libglvnd@$VERSION.tar.gz
exit
