#!/bin/sh -e

DEPENDENCIES="meson"
INFO="The GL Vendor-Neutral Dispatch library"
PRETTY_NAME="libglvnd"
SOURCES="https://gitlab.freedesktop.org/glvnd/libglvnd/-/archive/v$VERSION/libglvnd-v$VERSION.tar.gz"
MAJOR="1"
MINOR="7"
PATCH="0"
VERSION="$MAJOR.$MINOR.$PATCH"
