#!/bin/sh -e

mkdir build
unzip -d build roboto-android.zip

mkdir -p "$DESTDIR/usr/share/fonts/TTF"
cp build/*.ttf "$DESTDIR/usr/share/fonts/TTF"

su
chown -R root:root $DESTDIR
cd $DESTDIR
tar -c * | gzip > ../ttf-roboto@$VERSION.tar.gz
exit
