#!/bin/sh -e

PRETTY_NAME=fonts:roboto
MAJOR=2
MINOR=138
PATCH=
VERSION=2.138

mkdir temporary-builddir
DESTDIR=temporary-builddir

curl --location --remote-name --skip-existing https://github.com/googlefonts/roboto/releases/download/v/roboto-android.zip
mkdir build
unzip -d build roboto-android.zip

mkdir -p "$DESTDIR/usr/share/fonts/TTF"
cp build/*.ttf "$DESTDIR/usr/share/fonts/TTF"

su
chown -R root:root $DESTDIR
tar -c -C $DESTDIR . | gzip > ../ttf-roboto@$VERSION.tar.gz
exit
