#!/bin/sh -e

DEPENDENCIES=""
INFO=""
PRETTY_NAME="fonts:roboto"
SOURCES="https://github.com/googlefonts/roboto/releases/download/v$VERSION/roboto-android.zip"
MAJOR="2"
MINOR="138"
VERSION="$MAJOR.$MINOR"
