#!/bin/sh -e

tar -xf m4-$VERSION.tar.xz
cd m4-$VERSION

./configure \
	--prefix=/usr \
	--disable-nls \
	--enable-threads=posix \
	--without-packager

make
make DESTDIR="$DESTDIR" install-strip

rm -rf "$DESTDIR/usr/share/info"
