#!/bin/sh -e

tar -xf libdrm-$VERSION.tar.xz
cd libdrm-$VERSION

meson setup \
	-Dprefix=/usr \
	-Dlibdir=/usr/lib \
	-Dbuildtype=release \
	-Ddefault_library=both \
	-Dudev=false \
	-Dcairo-tests=disabled \
	-Dvalgrind=disabled \
	-Dtests=false \
	-Dman-pages=disabled \
	build

meson -C build compile
meson -C build install -d "$DESTDIR"

find "$DESTDIR/usr/lib" -type f -name '*.a'   -exec strip --strip-unneeded {} \;
find "$DESTDIR/usr/lib" -type f -name '*.so*' -exec strip --strip-unneeded {} \;
