#!/bin/sh -e

echo "This package is just a stub, edit its build parameters and remove this line"
exit 1

tar -xf libdrm-$VERSION.tar.xz
cd libdrm-$VERSION

meson setup \
	-Dprefix=/usr \
	-Dlibdir=/usr/lib \
	-Dbuildtype=release \
	-Ddefault_library=both \
	-Dudev=false \
	-Dcairo-tests=disabled \
	-Dvalgrind=disabled \
	-Dtests=false \
	-Dman-pages=disabled \
	-Dintel=disabled \
	-Dradeon=disabled \
	-Damdgpu=disabled \
	-Dnouveau=disabled \
	-Dvmwgfx=disabled \
	-Domap=disabled \
	-Dexynos=disabled \
	-Dfreedreno=disabled \
	-Dtegra=disabled \
	-Dvc4=disabled \
	-Detnaviv=disabled \
	build

meson -C build compile
meson -C build install -d "$DESTDIR"

find "$DESTDIR/usr/lib" -type f -name '*.a'   -exec strip --strip-unneeded {} \;
find "$DESTDIR/usr/lib" -type f -name '*.so*' -exec strip --strip-unneeded {} \;
