#!/bin/sh -e

tar -xf $VERSION.tar.gz
cd libudev-zero-$VERSION

make PREFIX=/usr
make PREFIX=/usr DESTDIR="$DESTDIR" install

find "$DESTDIR/usr/lib" -type f -name '*.a'  -exec strip --strip-unneeded {} \;
find "$DESTDIR/usr/lib" -type f -name '*.so' -exec strip --strip-unneeded {} \;
