#!/bin/sh -e

PRETTY_NAME=util-linux
MAJOR=2
MINOR=40
PATCH=4
VERSION=2.40.4

mkdir temporary-builddir
DESTDIR=temporary-builddir

curl --location --remote-name --skip-existing https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v./util-linux-$VERSION.tar.xz

xz -cd util-linux-$VERSION.tar.xz | tar -x
cd util-linux-$VERSION

./configure \
	--prefix=/usr \
	--libdir=/usr/lib \
	--bindir=/usr/bin \
	--sbindir=/usr/bin \
	--enable-usrdir-path \
	--enable-fs-paths-default=/usr/bin \
	--disable-all-programs \
	--disable-bash-completion \
	--disable-makeinstall-chown \
	--enable-libmount \
	--enable-libblkid \
	--enable-libsmartcols \
	--enable-fsck \
	--enable-wipefs \
	--enable-mkfs \
	--without-udev \
	--without-readline \
	--without-libmagic \
	--without-cap-ng \
	--without-python

make
make DESTDIR="$DESTDIR" install-strip

rm -rf "$DESTDIR/usr/share/man/man3"
find $DESTDIR -type f -name '*.la' -delete

# For some reason, this directory is created anyway
rmdir "$DESTDIR/usr/sbin"

su
chown -R root:root $DESTDIR
cd $DESTDIR
tar -c * | gzip > ../util-linux@$VERSION.tar.gz
exit
