#!/bin/sh -e

xz -cd util-linux-$VERSION.tar.xz | tar -x
cd util-linux-$VERSION

./configure \
	--prefix=/usr \
	--libdir=/usr/lib \
	--bindir=/usr/bin \
	--sbindir=/usr/bin \
	--enable-static-programs=mount,umount \
	--enable-usrdir-path \
	--enable-fs-paths-default=/usr/bin \
	--disable-all-programs \
	--disable-bash-completion \
	--disable-makeinstall-chown \
	--enable-blkid \
	--enable-fsck \
	--enable-wipefs \
	--enable-mkfs \
	--enable-mount \
	--enable-mountpoint \
	--enable-libsmartcols \
	--enable-libblkid \
	--enable-libmount \
	--enable-libuuid \
	--without-udev \
	--without-readline \
	--without-libmagic \
	--without-cap-ng \
	--without-python

make
make DESTDIR="$DESTDIR" install-strip

rm -rf "$DESTDIR/usr/share/man/man3"
find $DESTDIR -type f -name '*.la' -delete

# For some reason, this directory is created anyway
rmdir "$DESTDIR/usr/sbin"
