#!/bin/sh -e

DEPENDENCIES="linux-headers zlib"
INFO="Various useful Linux utilities"
PRETTY_NAME="util-linux"
SOURCES="https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v$MAJOR.$MINOR/util-linux-$VERSION.tar.xz"
MAJOR="2"
MINOR="40"
PATCH="4"
VERSION="$MAJOR.$MINOR.$PATCH"
