#!/bin/sh -e

gzip -cd dtc-$VERSION.tar.gz | tar -x
cd dtc-$VERSION

export NO_PYTHON=1
export NO_VALGRIND=1
export NO_YAML=1

make PREFIX=/usr
make PREFIX=/usr DESTDIR="$DESTDIR" install

su
chown -R root:root $DESTDIR
exit
