#!/bin/sh -e

DEPENDENCIES="pkgconf"
INFO=""
PRETTY_NAME="dtc"
SOURCES="https://git.kernel.org/pub/scm/utils/dtc/dtc.git/snapshot/dtc-$VERSION.tar.gz"
MAJOR="1"
MINOR="7"
PATCH="0"
VERSION="$MAJOR.$MINOR.$PATCH"
