#!/bin/sh -e

gzip -cd toybox-$VERSION.tar.gz | tar -x
cd toybox-$VERSION

make defconfig

CFLAGS="$CFLAGS -static" LDFLAGS="$LDFLAGS -static" make sed
install -Dm755 sed "$DESTDIR/usr/bin/sed"
strip --strip-unneeded "$DESTDIR/usr/bin/sed"

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > sed@$VERSION.tar.gz
exit
