#!/bin/sh -e

xz -cd bsdutils-$VERSION.tar.xz | tar -x
cd bsdutils-$VERSION/src/sed

cp ../../compat/strlcat.c .
cp ../../compat/strlcpy.c .
cp ../../include/compat.h .
cp ../../include/sys/cdefs.h .

sed -i 's|<sys/cdefs.h>|"cdefs.h"|g' *.c

$CC -c *.c
$CC -static *.o -o sed

install -Dm755 -t "$DESTDIR/usr/bin" sed
install -Dm644 -t "$DESTDIR/usr/share/man/man1" sed.1

strip --strip-unneeded "$DESTDIR/usr/bin/sed"
