#!/bin/sh -e

DEPENDENCIES=""
INFO="Stream editor"
PRETTY_NAME="sed"
SOURCES="https://github.com/dcantrell/bsdutils/releases/download/v$VERSION/bsdutils-$VERSION.tar.xz"
SOURCES="$SOURCES patches/add-missing-typedefs.patch"
MAJOR="13"
MINOR="1"
VERSION="$MAJOR.$MINOR"
