#!/bin/sh -e

DEPENDENCIES=""
INFO="GNU stream editor"
PRETTY_NAME="sed"
SOURCES="https://github.com/dcantrell/bsdutils/releases/download/v$VERSION/bsdutils-$VERSION.tar.xz"
MAJOR="13"
MINOR="1"
VERSION="$MAJOR.$MINOR"
