#!/bin/sh -e

bzip2 -cd expat-$VERSION.tar.bz2 | tar -x
cd expat-$VERSION

./configure \
	--prefix=/usr \
	--without-xmlwf \
	--without-examples \
	--without-tests \
	--without-docbook

make
make DESTDIR="$DESTDIR" install-strip

rm -rf "$DESTDIR/usr/share"
find $DESTDIR -type f -name '*.la' -delete

su
chown -R root:root $DESTDIR
cd $DESTDIR
tar -c * | gzip > ../expat@$VERSION.tar.gz
exit
