#!/bin/sh -e

PRETTY_NAME=expat
MAJOR=2
MINOR=6
PATCH=2
VERSION=2.6.2

mkdir temporary-builddir
DESTDIR="$PWD/temporary-builddir"

curl --location --remote-name --skip-existing https://github.com/libexpat/libexpat/releases/download/R_/expat-.tar.bz2
bzip2 -cd expat-$VERSION.tar.bz2 | tar -x
cd expat-$VERSION

./configure \
	--prefix=/usr \
	--without-xmlwf \
	--without-examples \
	--without-tests \
	--without-docbook

make
make DESTDIR=$DESTDIR install-strip

rm -rf "$DESTDIR/usr/share"
find $DESTDIR -type f -name '*.la' -delete

su
chown -R root:root $DESTDIR
tar -zcC $DESTDIR . | gzip > ../expat@$VERSION.tar.gz
exit
