#!/bin/sh -e

DEPENDENCIES=""
INFO="Stream-oriented XML parser library"
PRETTY_NAME="expat"
SOURCES="https://github.com/libexpat/libexpat/releases/download/R_$MAJOR_$MINOR_$PATCH/expat-$VERSION.tar.bz2"
MAJOR="2"
MINOR="6"
PATCH="2"
VERSION="$MAJOR.$MINOR.$PATCH"
