#!/bin/sh -e

gzip -d xz-$VERSION.tar.gz | tar -x
cd xz-$VERSION

./configure \
    --prefix=/usr \
    --disable-doc \
    --disable-nls

make
make DESTDIR="$DESTDIR" install-strip

find $DESTDIR -type f -name '*.la' -delete
