#!/bin/sh -e

PRETTY_NAME=xz
MAJOR=5
MINOR=6
PATCH=4
VERSION=5.6.4

mkdir temporary-builddir
DESTDIR="$PWD/temporary-builddir"

curl --location --remote-name --skip-existing https://tukaani.org/xz/xz-$VERSION.tar.gz

gzip -cd xz-$VERSION.tar.gz | tar -x
cd xz-$VERSION

./configure \
    --prefix=/usr \
    --disable-doc \
    --disable-nls

make
make DESTDIR=$DESTDIR install-strip

find $DESTDIR -type f -name '*.la' -delete

doas chown -R root:root $DESTDIR
doas sh -c "tar -zcC $DESTDIR . | gzip > ../xz@$VERSION.tar.gz"
