#!/bin/sh -e

tar -xf mandoc-$VERSION.tar.gz
cd mandoc-$VERSION

patch -p1 < ../mandoc-no-warn.patch

sed -i 's/"more -s"/"less"/g' main.c
sed -i "s/CC=.*/CC=$CC/" configure

cat > configure.local << EOF
PREFIX=/usr
MANDIR=/usr/share/man
LIBDIR=/usr/lib
SBINDIR=/usr/bin
LN="ln -sf"
EOF

./configure

make
make base-install

find "$DESTDIR/usr/bin" -type f -exec strip --strip-unneeded {} \; -exec chmod 755 {} \;
