#!/bin/sh -e

gzip -cd $VERSION.tar.gz | tar -x
cd luaexpat-$VERSION

patch -p1 < ../both-static-and-dynamic.patch

make
make install

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > lua-expat@$VERSION.tar.gz
exit
