#!/bin/sh -e

xz -cd libevdev-$VERSION.tar.xz | tar -x
cd libevdev-$VERSION

./configure --prefix=/usr

make
make DESTDIR="$DESTDIR" install-strip

rm -rf "$DESTDIR/usr/share/man/man3"
find $DESTDIR -type f -name '*.la' -delete

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > libevdev@$VERSION.tar.gz
exit
