#!/bin/sh -e

PRETTY_NAME=libevdev
MAJOR=1
MINOR=13
PATCH=1
VERSION=1.13.1

mkdir temporary-builddir
DESTDIR="$PWD/temporary-builddir"

curl --location --remote-name --skip-existing https://freedesktop.org/software/libevdev/libevdev-$VERSION.tar.xz

xz -cd libevdev-$VERSION.tar.xz | tar -x
cd libevdev-$VERSION

./configure --prefix=/usr

make
make DESTDIR=$DESTDIR install-strip

rm -rf "$DESTDIR/usr/share/man/man3"
find $DESTDIR -type f -name '*.la' -delete

doas chown -R root:root $DESTDIR
doas sh -c "tar -zcC $DESTDIR . | gzip > ../libevdev@$VERSION.tar.gz"
