#!/bin/sh -e

PRETTY_NAME=wayland
MAJOR=1
MINOR=24
PATCH=0
VERSION=1.24.0

if [ ! -f $0 ]; then return; fi

mkdir temporary-distdir
DESTDIR="$PWD/temporary-distdir"

curl --location --remote-name --skip-existing https://gitlab.freedesktop.org/wayland/wayland/-/releases/$VERSION/downloads/wayland-$VERSION.tar.xz

xz -cd wayland-$VERSION.tar.xz | tar -x
cd wayland-$VERSION

muon setup \
	-D prefix=/usr \
	-D buildtype=release \
	-D default_library=both \
	-D tests=false \
	-D documentation=false \
	-D dtd_validation=false \
	build

ninja -C build
muon -C build install -d "$DESTDIR"

find "$DESTDIR/usr/lib" -type f -name '*.a'   -exec strip --strip-unneeded {} \;
find "$DESTDIR/usr/lib" -type f -name '*.so*' -exec strip --strip-unneeded {} \;
strip --strip-unneeded "$DESTDIR/usr/bin/wayland-scanner"

doas chown -R root:root $DESTDIR
doas sh -c "tar -zcC $DESTDIR . | gzip > ../wayland@$VERSION.tar.gz"
CALLER_UID=$(id -un)
CALLER_GID=$(id -gn)
doas chown -R $CALLER_UID:$CALLER_GID $DESTDIR
