#!/bin/sh -e

PRETTY_NAME=wayland
MAJOR=1
MINOR=22
PATCH=0
VERSION=1.22.0

mkdir temporary-builddir
DESTDIR="$PWD/temporary-builddir"

curl --location --remote-name --skip-existing https://gitlab.freedesktop.org/wayland/wayland/-/releases//downloads/wayland-$VERSION.tar.xz

xz -cd wayland-$VERSION.tar.xz | tar -x
cd wayland-$VERSION

meson setup \
	-Dprefix=/usr \
	-Dbuildtype=release \
	-Ddefault_library=both \
	-Dtests=false \
	-Ddocumentation=false \
	-Ddtd_validation=false \
	build

meson -C build compile
meson -C build install -d "$DESTDIR"

find "$DESTDIR/usr/lib" -type f -name '*.a'   -exec strip --strip-unneeded {} \;
find "$DESTDIR/usr/lib" -type f -name '*.so*' -exec strip --strip-unneeded {} \;
strip --strip-unneeded "$DESTDIR/usr/bin/wayland-scanner"

doas chown -R root:root $DESTDIR
doas sh -c "tar -zcC $DESTDIR . | gzip > ../wayland@$VERSION.tar.gz"
