#!/bin/sh -e

DEPENDENCIES="expat flex libffi meson pkgconf"
INFO="Wayland protocol libraries"
PRETTY_NAME="wayland"
SOURCES="https://gitlab.freedesktop.org/wayland/wayland/-/releases/$VERSION/downloads/wayland-$VERSION.tar.xz"
MAJOR="1"
MINOR="22"
PATCH="0"
VERSION="$MAJOR.$MINOR.$PATCH"
