#!/bin/sh -e

tar -xf pigz-$VERSION.tar.gz
cd pigz-$VERSION

$CC -c pigz.c -DNOZOPFLI
$CC -c yarn.c -DNOZOPFLI
$CC -c try.c  -DNOZOPFLI

$CC -static -o pigz *.o -lz

install -Dm755 -t "$DESTDIR/usr/bin" pigz
install -Dm644 -t "$DESTDIR/usr/share/man/man1" pigz.1

ln -s pigz "$DESTDIR/usr/bin/gzip"
