#!/bin/sh -e

xz -cd grep-$VERSION.tar.xz | tar -x
cd grep-$VERSION

export CFLAGS="$CFLAGS -Wno-error -static"

./configure \
	--prefix=/usr \
	--disable-nls \
	--enable-threads=posix \
	--without-packager

make
make DESTDIR="$DESTDIR" install-strip

rm -rf "$DESTDIR/usr/share/info"

ln -sf grep "$DESTDIR/usr/bin/ggrep"

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > grep@$VERSION.tar.gz
exit
