#!/bin/sh -e

PRETTY_NAME=pkgconf
MAJOR=2
MINOR=3
PATCH=0
VERSION=2.3.0

mkdir temporary-builddir
DESTDIR=temporary-builddir

curl --location --remote-name --skip-existing https://distfiles.ariadne.space/pkgconf/pkgconf-$VERSION.tar.xz

xz -cd pkgconf-$VERSION.tar.xz | tar -x
cd pkgconf-$VERSION

./configure \
	--prefix=/usr \
	--sysconfdir=/etc
	
make
make DESTDIR="$DESTDIR" install-strip

ln -s pkgconf "$DESTDIR/usr/bin/pkg-config"

rm -rf "$DESTDIR/usr/share/doc"
find $DESTDIR -type f -name '*.la' -delete

su
chown -R root:root $DESTDIR
cd $DESTDIR
tar -c * | gzip > ../pkgconf@$VERSION.tar.gz
exit
