#!/bin/sh -e

xz -cd pkgconf-$VERSION.tar.xz | tar -x
cd pkgconf-$VERSION

./configure \
	--prefix=/usr \
	--sysconfdir=/etc
	
make
make DESTDIR="$DESTDIR" install-strip

ln -s pkgconf "$DESTDIR/usr/bin/pkg-config"

rm -rf "$DESTDIR/usr/share/doc"
find $DESTDIR -type f -name '*.la' -delete
