#!/bin/sh -e

tar -xf linux-$VERSION.tar.xz
cd linux-$VERSION

make LLVM=1 LLVM_IAS=1 HOSTCC="$CC" headers

# The headers require rsync for installation, this command
# simply does the equivalent using find, mkdir and cp.
find usr/include -name \*.h -type f | while read -r file; do
    mkdir -p "$1/${file%/*}"
    cp -f "$file" "$1/$file"
done
