#!/bin/sh -e

cd awk.git

sed -i 's/gcc/cc/g' makefile

make CFLAGS="$CFLAGS -static"

install -Dm755 a.out   "$DESTDIR/usr/bin/awk"
install -Dm644 awk.1   "$DESTDIR/usr/share/man/man1/awk.1" 
install -Dm644 LICENSE "$DESTDIR/usr/share/LICENSES/awk.license"

strip --strip-unneeded "$DESTDIR/usr/bin/awk"

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > awk@$VERSION.tar.gz
exit
