#!/bin/sh -e

gzip -cd $VERSION.tar.gz | tar -x
cd tz-$VERSION

sed -i 's|sbin|bin|g' Makefile

make
make DESTDIR="$DESTDIR" install

rm -rf "$DESTDIR/etc"
rm -rf "$DESTDIR/usr/share/man/man3"

for t in africa asia australasia europe northamerica southamerica
do
	./zic -d "$DESTDIR/usr/share/zoneinfo" $t
	./zic -d "$DESTDIR/usr/share/zoneinfo/right" -L leapseconds $t
done

# POSIX compliance (?)
./zic -d "$DESTDIR/usr/share/zoneinfo" -p America/New_York

strip --strip-unneeded "$DESTDIR/usr/bin/zic"
strip --strip-unneeded "$DESTDIR/usr/bin/zdump"

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > tzdata@$VERSION.tar.gz
exit
