#!/bin/sh -e

DEPENDENCIES=""
INFO="Timezone data (/usr/share/zoneinfo) and utilities (tzselect/zic/zdump)"
PRETTY_NAME="tzdata"
SOURCES="https://github.com/eggert/tz/archive/refs/tags/$VERSION.tar.gz"
MAJOR="2025"
MINOR="a"
VERSION="$MAJOR$MINOR"
