#!/bin/sh -e

PRETTY_NAME=fonts:gentium-plus
MAJOR=6
MINOR=200
PATCH=
VERSION=6.200

mkdir temporary-builddir
DESTDIR=temporary-builddir

curl --location --remote-name --skip-existing https://software.sil.org/downloads/r/gentium/GentiumPlus-$VERSION.zip

mkdir build
unzip -d build GentiumPlus-$VERSION.zip

mkdir -p "$DESTDIR/usr/share/fonts/TTF"
cp ttf/*.ttf "$DESTDIR/usr/share/fonts/TTF"

install -Dm644 OFL.txt "$DESTDIR/usr/share/LICENSES/ttf-gentium-plus.license"

su
chown -R root:root $DESTDIR
tar -c -C $DESTDIR . | gzip > ../ttf-gentium-plus@$VERSION.tar.gz
exit
