#!/bin/sh -e

PRETTY_NAME=fonts:gentium-plus
MAJOR=6
MINOR=200
PATCH=
VERSION=6.200

if [ ! -f $0 ]; then return; fi

mkdir temporary-distdir
DESTDIR="$PWD/temporary-distdir"

curl --location --remote-name --skip-existing https://software.sil.org/downloads/r/gentium/GentiumPlus-$VERSION.zip

mkdir build
unzip -d build GentiumPlus-$VERSION.zip

mkdir -p "$DESTDIR/usr/share/fonts/TTF"
cp ttf/*.ttf "$DESTDIR/usr/share/fonts/TTF"

install -Dm644 OFL.txt "$DESTDIR/usr/share/LICENSES/ttf-gentium-plus.license"

doas chown -R root:root $DESTDIR
doas sh -c "tar -zcC $DESTDIR . | gzip > ../ttf-gentium-plus@$VERSION.tar.gz"
CALLER_UID=$(id -un)
CALLER_GID=$(id -gn)
doas chown -R $CALLER_UID:$CALLER_GID $DESTDIR
