#!/bin/sh -e

tar -xf bc-$VERSION.tar.gz
cd bc-$VERSION

./configure \
	--prefix=/usr \
	--enable-editline \
	--disable-generated-tests \
	--disable-nls \
	--disable-problematic-tests

make
make install

find "$DESTDIR/usr/bin" -type f -exec strip --strip-unneeded {} \;
