#!/bin/sh -e

gzip -d wlroots-$VERSION.tar.gz | tar -x
cd wlroots-$VERSION

meson setup \
	-Dprefix=/usr \
	-Ddefault_library=both \
	-Dexamples=false \
	-Dbackends=libinput,drm \
	-Dxcb-errors=disabled \
	-Drenderers=gles2 \
	build

meson -C build compile
meson -C build install -d "$DESTDIR"

find "$DESTDIR/usr/lib" -type f -name '*.a'   -exec strip --strip-unneeded {} \;
find "$DESTDIR/usr/lib" -type f -name '*.so*' -exec strip --strip-unneeded {} \;
