#!/bin/sh -e

PRETTY_NAME=wlroots
MAJOR=0
MINOR=17
PATCH=3
VERSION=0.17.3

mkdir temporary-builddir
DESTDIR=temporary-builddir

curl --location --remote-name --skip-existing https://gitlab.freedesktop.org/wlroots/wlroots/-/archive//wlroots-$VERSION.tar.gz

gzip -cd wlroots-$VERSION.tar.gz | tar -x
cd wlroots-$VERSION

meson setup \
	-Dprefix=/usr \
	-Ddefault_library=both \
	-Dexamples=false \
	-Dbackends=libinput,drm \
	-Dxcb-errors=disabled \
	-Drenderers=gles2 \
	build

meson -C build compile
meson -C build install -d "$DESTDIR"

find "$DESTDIR/usr/lib" -type f -name '*.a'   -exec strip --strip-unneeded {} \;
find "$DESTDIR/usr/lib" -type f -name '*.so*' -exec strip --strip-unneeded {} \;

su
chown -R root:root $DESTDIR
cd $DESTDIR
tar -c * | gzip > ../wlroots@$VERSION.tar.gz
exit
