#!/bin/sh -e

DEPENDENCIES="flex hwdata libdrm libdisplay-info libinput libudev-zero libxkbcommon linux-headers mesa meson pixman seatd wayland wayland-protocols"
INFO="Pluggable, composable, unopinionated modules for building a Wayland compositor"
PRETTY_NAME="wlroots"
SOURCES="https://gitlab.freedesktop.org/wlroots/wlroots/-/archive/$VERSION/wlroots-$VERSION.tar.gz"
MAJOR="0"
MINOR="17"
PATCH="3"
VERSION="$MAJOR.$MINOR.$PATCH"
