#!/bin/sh -e

tar -xf flex-$VERSION.tar.gz
cd flex-$VERSION

./configure \
	--prefix=/usr \
	ac_cv_func_malloc_0_nonnull=yes \
	ac_cv_func_realloc_0_nonnull=yes

make
make DESTDIR="$DESTDIR" install

ln -sf flex "$DESTDIR/usr/bin/lex"

rm -rf "$DESTDIR/usr/share/doc"
rm -rf "$DESTDIR/usr/share/info"

find $DESTDIR -type f -name '*.la' -delete
