#!/bin/sh -e

xz -cd mpfr-$VERSION.tar.xz | tar -x
cd mpfr-$VERSION

./configure \
	--prefix=/usr \
	--enable-shared \
	--enable-thread-safe

make
make DESTDIR="$DESTDIR" install

rm -rf "$DESTDIR/usr/share"
find $DESTDIR -type f -name '*.la' -delete

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > libmpfr@$VERSION.tar.gz
exit
