#!/bin/sh -e

PRETTY_NAME=mpfr
MAJOR=4
MINOR=2
PATCH=1
VERSION=4.2.1

mkdir temporary-builddir
DESTDIR="$PWD/temporary-builddir"

curl --location --remote-name --skip-existing https://www.mpfr.org/mpfr-current/mpfr-$VERSION.tar.xz

xz -cd mpfr-$VERSION.tar.xz | tar -x
cd mpfr-$VERSION

./configure \
	--prefix=/usr \
	--enable-shared \
	--enable-thread-safe

make
make DESTDIR=$DESTDIR install

rm -rf "$DESTDIR/usr/share"
find $DESTDIR -type f -name '*.la' -delete

doas chown -R root:root $DESTDIR
doas sh -c "tar -zcC $DESTDIR . | gzip > ../libmpfr@$VERSION.tar.gz"
