#!/bin/sh -e

cd nextvi.git

export CFLAGS="$CFLAGS -static" 

CC=cc ./cbuild.sh

install -Dm755 vi "$DESTDIR/usr/bin/vi"
strip --strip-unneeded "$DESTDIR/usr/bin/vi"

su
chown -R root:root $DESTDIR
cd $DESTDIR
tar -c * | gzip > ../nextvi@$VERSION.tar.gz
exit
