#!/bin/sh -e

PRETTY_NAME=hwdata
MAJOR=0
MINOR=401
PATCH=
VERSION=0.401

if [ ! -f $0 ]; then return; fi

mkdir temporary-distdir
DESTDIR="$PWD/temporary-distdir"

curl --location --remote-name --skip-existing https://github.com/vcrhonek/hwdata/archive/refs/tags/v$VERSION.tar.gz

gzip -cd v$VERSION.tar.gz | tar -x
cd hwdata-$VERSION

./configure \
	--prefix=/usr \
	--disable-blacklist

make DESTDIR=$DESTDIR install

doas chown -R root:root $DESTDIR
doas sh -c "tar -zcC $DESTDIR . | gzip > ../hwdata@$VERSION.tar.gz"
CALLER_UID=$(id -un)
CALLER_GID=$(id -gn)
doas chown -R $CALLER_UID:$CALLER_GID $DESTDIR
