#!/bin/sh -e

gzip -d $VERSION.tar.gz | tar -x
cd markupsafe-$VERSION

python setup.py build
python setup.py install \
	--prefix=/usr \
	--root="$DESTDIR"

find "$DESTDIR/usr/lib" -type f -name '*.so' -exec strip --strip-unneeded {} \;
