#!/bin/sh -e

PRETTY_NAME=python:markupsafe
MAJOR=2
MINOR=1
PATCH=5
VERSION=2.1.5

mkdir temporary-builddir
DESTDIR="$PWD/temporary-builddir"

curl --location --remote-name --skip-existing https://github.com/pallets/markupsafe/archive/refs/tags/.tar.gz
gzip -cd $VERSION.tar.gz | tar -x
cd markupsafe-$VERSION

python setup.py build
python setup.py install \
	--prefix=/usr \
	--root="$DESTDIR"

find "$DESTDIR/usr/lib" -type f -name '*.so' -exec strip --strip-unneeded {} \;

doas chown -R root:root $DESTDIR
doas sh -c "tar -zcC $DESTDIR . | gzip > ../markupsafe@$VERSION.tar.gz"
