#!/bin/sh -e

DEPENDENCIES="python"
INFO=""
PRETTY_NAME="python:markupsafe"
SOURCES="https://github.com/pallets/markupsafe/archive/refs/tags/$VERSION.tar.gz"
MAJOR="2"
MINOR="1"
PATCH="5"
VERSION="$MAJOR.$MINOR.$PATCH"
