#!/bin/sh -e

PRETTY_NAME=bzip2
MAJOR=1
MINOR=0
PATCH=8
VERSION=1.0.8

if [ ! -f $0 ]; then return; fi

mkdir temporary-distdir
DESTDIR="$PWD/temporary-distdir"

curl --location --remote-name --skip-existing https://sourceware.org/pub/bzip2/bzip2-$VERSION.tar.gz

gzip -cd bzip2-$VERSION.tar.gz | tar -x
cd bzip2-$VERSION

make CC="$CC $CFLAGS $LDFLAGS" -f Makefile-libbz2_so
make CC="$CC $CFLAGS $LDFLAGS" bzip2

install -Dm755 bzip2  "$DESTDIR/usr/bin/bzip2"
install -Dm755 bzdiff "$DESTDIR/usr/bin/bzdiff"
install -Dm755 bzgrep "$DESTDIR/usr/bin/bzgrep"
install -Dm755 bzmore "$DESTDIR/usr/bin/bzmore"

ln -sf bzip2 "$DESTDIR/usr/bin/bunzip2"
ln -sf bzip2 "$DESTDIR/usr/bin/bzcat"

install -Dm644 -t "$DESTDIR/usr/share/man/man1" bzip2.1 
install -Dm644 -t "$DESTDIR/usr/include"        bzlib.h 

install -Dm644 libbz2.so.$VERSION "$DESTDIR/usr/lib/libbz2.so.$VERSION"
install -Dm644 libbz2.a           "$DESTDIR/usr/lib/libbz2.a"

strip --strip-unneeded "$DESTDIR/usr/bin/bzip2"
strip --strip-unneeded "$DESTDIR/usr/lib/libbz2.so.$VERSION"
strip --strip-unneeded "$DESTDIR/usr/lib/libbz2.a"

ln -sf "libbz2.so.$VERSION" "$DESTDIR/usr/lib/libbz2.so"
ln -sf "libbz2.so.$VERSION" "$DESTDIR/usr/lib/libbz2.so.$MAJOR"
ln -sf "libbz2.so.$VERSION" "$DESTDIR/usr/lib/libbz2.so.$MAJOR.$MINOR"

doas chown -R root:root $DESTDIR
doas sh -c "tar -zcC $DESTDIR . | gzip > ../bzip2@$VERSION.tar.gz"
CALLER_UID=$(id -un)
CALLER_GID=$(id -gn)
doas chown -R $CALLER_UID:$CALLER_GID $DESTDIR
