#!/bin/sh -e

DEPENDENCIES=""
INFO="A high-quality data compressor"
PRETTY_NAME="bzip2"
SOURCES="https://sourceware.org/pub/bzip2/bzip2-$VERSION.tar.gz"
MAJOR="1"
MINOR="0"
PATCH="8"
VERSION="$MAJOR.$MINOR.$PATCH"
