#!/bin/sh -e

xz -cd m4-$VERSION.tar.xz | tar -x
cd m4-$VERSION

./configure \
	--prefix=/usr \
	--disable-nls \
	--enable-threads=posix \
	--without-packager

make
make DESTDIR="$DESTDIR" install-strip

rm -rf "$DESTDIR/usr/share/info"

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > m4@$VERSION.tar.gz
exit
