#!/bin/sh -e

PRETTY_NAME=m4
MAJOR=1
MINOR=4
PATCH=19
VERSION=1.4.19

mkdir temporary-builddir
DESTDIR=temporary-builddir

curl --location --remote-name --skip-existing https://ftp.gnu.org/gnu/m4/m4-$VERSION.tar.xz

xz -cd m4-$VERSION.tar.xz | tar -x
cd m4-$VERSION

./configure \
	--prefix=/usr \
	--disable-nls \
	--enable-threads=posix \
	--without-packager

make
make DESTDIR="$DESTDIR" install-strip

rm -rf "$DESTDIR/usr/share/info"

su
chown -R root:root $DESTDIR
cd $DESTDIR
tar -c * | gzip > ../m4@$VERSION.tar.gz
exit
