#!/bin/sh -e

xz -cd iproute2-$VERSION.tar.xz | tar -x
cd iproute2-$VERSION

# From upstream. Will be removed on next version
patch -p1 < ../missing-include-of-time.patch

sed -i 's/CC := gcc/CC ?= gcc/g' Makefile

./configure --include_dir /usr/include

make KERNEL_INCLUDE=y

install -Dm755 ip/ip "$DESTDIR/usr/bin/ip"
install -Dm755 tc/tc "$DESTDIR/usr/bin/tc"

install -Dm0644 include/libnetlink.h "$DESTDIR/usr/include/libnetlink.h"
install -Dm0644 lib/libnetlink.a     "$DESTDIR/usr/lib/libnetlink.a"

mkdir -p "$DESTDIR/usr/share/man/man8"
cp man/man8/ip* "$DESTDIR/usr/share/man/man8"
cp man/man8/tc* "$DESTDIR/usr/share/man/man8"

strip --strip-unneeded "$DESTDIR/usr/bin/ip"
strip --strip-unneeded "$DESTDIR/usr/bin/tc"
strip --strip-unneeded "$DESTDIR/usr/lib/libnetlink.a"

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > iproute2@$VERSION.tar.gz
exit
