#!/bin/sh -e

DEPENDENCIES="bison flex linux-headers pkgconf xz"
INFO="kernel routing and traffic control utilities"
PRETTY_NAME="iproute2"
SOURCES="https://www.kernel.org/pub/linux/utils/net/iproute2/iproute2-$VERSION.tar.xz"
SOURCES="$SOURCES patches/fix-missing-includes.patch"
MAJOR="6"
MINOR="12"
PATCH="0"
VERSION="$MAJOR.$MINOR.$PATCH"
