#!/bin/sh -e

gzip -cd v$VERSION.tar.gz | tar -x
cd mdevd-$VERSION

./configure \
	--prefix=/usr \
	--enable-static-libc

make
make DESTDIR="$DESTDIR" install

install -Dm644 ../mdev.conf "$DESTDIR/etc/mdev.conf"
install -Dm755 ../mdevd.run  "$DESTDIR/etc/sv/mdevd/run"
ln -sf /run/runit/supervise.mdevd "$DESTDIR/etc/sv/mdevd/supervise"

strip --strip-unneeded "$DESTDIR/usr/bin/mdevd"
strip --strip-unneeded "$DESTDIR/usr/bin/mdevd-coldplug"

rm -rf "$DESTDIR/usr/include"

su
chown -R root:root $DESTDIR
exit
