#!/bin/sh -e

xz -cd gmp-$VERSION.tar.xz | tar -x
cd gmp-$VERSION

./configure \
	--prefix=/usr \
	--localstatedir=/var/state/gmp \
	--enable-cxx \
	--enable-fat \
	--with-pic

make
make DESTDIR="$DESTDIR" install

rm -rf "$DESTDIR/usr/share"
find $DESTDIR -type f -name '*.la' -delete

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > libgmp@$VERSION.tar.gz
exit
