#!/bin/sh -e

PRETTY_NAME=mime-types
MAJOR=
MINOR=
PATCH=
VERSION=git

mkdir temporary-builddir
DESTDIR="$PWD/temporary-builddir"

curl https://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types | grep -v '#' - > mime.types

install -Dm644 mime.types "$DESTDIR/etc/mime.types"

doas chown -R root:root $DESTDIR
doas sh -c "tar -zcC $DESTDIR . | gzip > mime-types@$VERSION.tar.gz"
