#!/bin/sh -e

grep -v '#' mime.types > mime-processed
install -Dm644 mime-processed "$DESTDIR/etc/mime.types"

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > mime-types@$VERSION.tar.gz
exit
