#!/bin/sh -e

gzip -cd pigz-$VERSION.tar.gz | tar -x
cd pigz-$VERSION

$CC -c *.c -DNOZOPFLI
$CC -static -o pigz *.o -lz

install -Dm755 pigz "$DESTDIR/usr/bin/pigz"
install -Dm644 pigz "$DESTDIR/usr/share/man/man1/pigz.1"

ln -sf pigz "$DESTDIR/usr/bin/gzip"
strip --strip-unneeded "$DESTDIR/usr/bin/pigz"

su
chown -R root:root $DESTDIR
cd $DESTDIR
tar -c * | gzip > ../pigz@$VERSION.tar.gz
exit
