#!/bin/sh -e

DEPENDENCIES="bison flex libgmp libmpc libmpfr zlib"
INFO=""
PRETTY_NAME="gcc"
SOURCES="https://gcc.gnu.org/pub/gcc/releases/gcc-$VERSION/gcc-$VERSION.tar.xz"
SOURCES="$SOURCES files/c99"
MAJOR="14"
MINOR="1"
PATCH="0"
VERSION="$MAJOR.$MINOR.$PATCH"
