#!/bin/sh -e

gzip -cd v$VERSION.tar.gz | tar -x

mkdir -p "$DESTDIR/usr/share/lua" 
cp -r fluent-lua-$VERSION/fluent "$DESTDIR/usr/share/lua"

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > lua-fluent@$VERSION.tar.gz
exit
