#!/bin/sh -e

DEPENDENCIES="lua penlight lua-cldr lua-epnf"
INFO=""
PRETTY_NAME="lua-fluent"
SOURCES="https://github.com/alerque/fluent-lua/archive/refs/tags/v$VERSION.tar.gz"
MAJOR="0"
MINOR="2"
PATCH="0"
VERSION="$MAJOR.$MINOR.$PATCH"
