#!/bin/sh -e

gzip -cd v$VERSION.tar.gz | tar -x

install -Dm644 -t "$DESTDIR/usr/share/lua/cldr"      cldr-lua-$VERSION/cldr/init.lua
install -Dm644 -t "$DESTDIR/usr/share/lua/cldr/data" cldr-lua-$VERSION/cldr/data/locales.lua

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > lua-cldr@$VERSION.tar.gz
exit
