#!/bin/sh -e

tar -xf v$VERSION.tar.gz

install -Dm644 -t "$DESTDIR/usr/share/lua/cldr"      cldr-lua-$VERSION/cldr/init.lua
install -Dm644 -t "$DESTDIR/usr/share/lua/cldr/data" cldr-lua-$VERSION/cldr/data/locales.lua
