#!/bin/sh -e

DEPENDENCIES="lua penlight"
INFO=""
PRETTY_NAME="lua-cldr"
SOURCES="https://github.com/alerque/cldr-lua/archive/refs/tags/v$VERSION.tar.gz"
MAJOR="0"
MINOR="3"
PATCH="0"
VERSION="$MAJOR.$MINOR.$PATCH"
