#!/bin/sh -e

echo "This package is just a stub, edit it build parameters and remove this line"
exit 1

tar -xf mesa-$VERSION.tar.xz
cd mesa-$VERSION

meson setup \
	-Dprefix=/usr \
	-Dsysconfdir=/etc \
	-Dmandir=/usr/share/man \
	-Dlocalstatedir=/var \
	-Dbuildtype=release \
	-Ddefault_library=both \
	-Dplatforms=wayland \
	-Dglx=disabled \
	-Degl=enabled \
	-Dgles1=enabled \
	-Dgles2=enabled \
	-Degl-native-platform=wayland \
	-Dvalgrind=disabled \
	-Dzstd=disabled \
	-Dglvnd=??? \
	-Dvulkan-drivers=??? \
	-Dgallium-drivers=??? \
	-Dllvm=??? \
	-Dshared-llvm=??? \
	build

meson -C build compile
meson -C build install -d "$DESTDIR"
