#!/bin/sh -e

PRETTY_NAME=lcms
MAJOR=2
MINOR=17
PATCH=
VERSION=2.17

if [ ! -f $0 ]; then return; fi

mkdir temporary-distdir
DESTDIR="$PWD/temporary-distdir"

curl --location --remote-name --skip-existing https://github.com/mm2/Little-CMS/archive/refs/tags/lcms$VERSION.tar.gz

gzip -cd lcms$VERSION.tar.gz | tar -x
cd Little-CMS-lcms$VERSION

./configure \
	--prefix=/usr \
	--enable-shared \
	--enable-static \
	--with-jpeg \
	--with-tiff \
	--with-zlib

make
make DESTDIR=$DESTDIR install-strip

find $DESTDIR -type f -name '*.la' -delete

doas chown -R root:root $DESTDIR
doas sh -c "tar -zcC $DESTDIR . | gzip > ../lcms@$VERSION.tar.gz"
CALLER_UID=$(id -un)
CALLER_GID=$(id -gn)
doas chown -R $CALLER_UID:$CALLER_GID $DESTDIR
