#!/bin/sh -e

# Taken one to one from KISS, with the compose-only patch slightly modified
# It would be interesting to bypass the config entirely and install
# tables straight away

PRETTY_NAME=libx11
MAJOR=1
MINOR=8
PATCH=12
VERSION=1.8.12

mkdir temporary-distdir
DESTDIR="$PWD/temporary-distdir"

curl --location --remote-name --skip-existing https://x.org/releases/individual/lib/libX11-$VERSION.tar.xz

xz -cd libX11-$VERSION.tar.xz | tar -x
cd libX11-$VERSION

patch -p1 < ../compose-only.patch

./configure \
	--prefix=/usr \
	--disable-specs \
	--disable-xkb \
	--without-fop \
	--without-xmlto

make -C nls
make DESTDIR=$DESTDIR -C nls install

doas chown -R root:root $DESTDIR
doas sh -c "tar -zcC $DESTDIR . | gzip > ../compose-tables@$VERSION.tar.gz"
CALLER_UID=$(id -un)
CALLER_GID=$(id -gn)
doas chown -R $CALLER_UID:$CALLER_GID $DESTDIR
