#!/bin/sh -e

PRETTY_NAME=libx11
MAJOR=1
MINOR=8
PATCH=7
VERSION=1.8.7

mkdir temporary-builddir
DESTDIR=temporary-builddir

curl --location --remote-name --skip-existing https://x.org/releases/individual/lib/libX11-$VERSION.tar.xz

xz -cd libX11-$VERSION.tar.xz | tar -x
cd libX11-$VERSION

patch -p1 < ../compose-only.patch

./configure \
	--prefix=/usr \
	--disable-specs \
	--disable-xkb \
	--without-fop \
	--without-xmlto \
	--with-keysymdefdir="/usr/include/X11"

make -C nls
make -C nls install

su
chown -R root:root $DESTDIR
cd $DESTDIR
tar -c * | gzip > ../compose-tables@$VERSION.tar.gz
exit
