#!/bin/sh -e

xz -cd libX11-$VERSION.tar.xz | tar -x
cd libX11-$VERSION

patch -p1 < ../compose-only.patch

./configure \
	--prefix=/usr \
	--disable-specs \
	--disable-xkb \
	--without-fop \
	--without-xmlto \
	--with-keysymdefdir="/usr/include/X11"

make -C nls
make -C nls install

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > compose-tables@$VERSION.tar.gz
exit
