#!/bin/sh -e

PRETTY_NAME=openssh
MAJOR=10
MINOR=2
PATCH=p1
VERSION=10.2p1

if [ ! -f $0 ]; then return; fi

mkdir temporary-distdir
DESTDIR="$PWD/temporary-distdir"

curl --location --remote-name --skip-existing https://ftp.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-$VERSION.tar.gz

gzip -cd openssh-$VERSION.tar.gz | tar -x
cd openssh-$VERSION

./configure \
	--prefix=/usr \
	--datadir=/usr/share/openssh \
	--sysconfdir=/etc/ssh \
	--sbindir=/usr/bin \
	--libexecdir=/usr/lib/openssh \
	--without-selinux \
	--with-privsep-user=nobody \
	--with-mantype=doc \
	--without-rpath \
	--enable-strip \
	--with-ssl-engine \
	--with-pid-dir=/run \
	--disable-wtmp \
	--disable-utmp \
	--disable-security-key

make
make DESTDIR=$DESTDIR install

install -Dm755 ../sshd.run "$DESTDIR/etc/sv/sshd/run" 
ln -sf /run/runit/supervise.sshd "$DESTDIR/etc/sv/sshd/supervise"

doas chown -R root:root $DESTDIR
doas sh -c "tar -zcC $DESTDIR . | gzip > ../openssh@$VERSION.tar.gz"
CALLER_UID=$(id -un)
CALLER_GID=$(id -gn)
doas chown -R $CALLER_UID:$CALLER_GID $DESTDIR
