#!/bin/sh -e

gzip -cd less-$VERSION.tar.gz | tar -x
cd less-$VERSION

./configure --prefix=/usr

make
make DESTDIR="$DESTDIR" install-strip

su
chown -R root:root $DESTDIR
cd $DESTDIR
tar -c * | gzip > ../less@$VERSION.tar.gz
exit
