#!/bin/sh -e

PRETTY_NAME=less
MAJOR=
MINOR=
PATCH=
VERSION=643

mkdir temporary-builddir
DESTDIR="$PWD/temporary-builddir"

curl --location --remote-name --skip-existing http://www.greenwoodsoftware.com/less/less-$VERSION.tar.gz

gzip -cd less-$VERSION.tar.gz | tar -x
cd less-$VERSION

./configure --prefix=/usr

make
make DESTDIR=$DESTDIR install-strip

doas chown -R root:root $DESTDIR
doas sh -c "tar -zcC $DESTDIR . | gzip > ../less@$VERSION.tar.gz"
