#!/bin/sh -e

gzip -cd less-$VERSION.tar.gz | tar -x
cd less-$VERSION

./configure --prefix=/usr

make
make DESTDIR="$DESTDIR" install-strip

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > less@$VERSION.tar.gz
exit
