#!/bin/sh -e

tar -xf $VERSION.tar.gz
cd $VERSION

make
make DESTDIR="$DESTDIR" install

rm -rf "$DESTDIR/etc"
set -- africa asia australasia europe northamerica southamerica

./zic -d "$DESTDIR/usr/share/zoneinfo" "$@"
./zic -d "$DESTDIR/usr/share/zoneinfo/posix" "$@"
./zic -d "$DESTDIR/usr/share/zoneinfo/right" -L leapseconds "$@"
./zic -d "$DESTDIR/usr/share/zoneinfo" -p America/New_York
