#!/bin/sh -e

tar -xf $VERSION.tar.gz
cd $VERSION

sed -i 's|sbin|bin|g' Makefile

make
make DESTDIR="$DESTDIR" install-strip

rm -rf "$DESTDIR/etc"

for t in africa asia australasia europe northamerica southamerica
do
	./zic -d "$DESTDIR/usr/share/zoneinfo" $t
	./zic -d "$DESTDIR/usr/share/zoneinfo/right" -L leapseconds $t
done

# Apparently, for POSIX compliance
./zic -d "$DESTDIR/usr/share/zoneinfo" -p America/New_York
