#!/bin/sh -e

PRETTY_NAME=libwebp
MAJOR=1
MINOR=6
PATCH=0
VERSION=1.6.0

mkdir temporary-distdir
DESTDIR="$PWD/temporary-distdir"

curl --location --remote-name --skip-existing https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-$VERSION.tar.gz

gzip -cd libwebp-$VERSION.tar.gz | tar -x
cd libwebp-$VERSION

./configure \
	--prefix=/usr \
	--enable-shared \
	--enable-static \
	--enable-libwebpmux \
	--enable-libwebpdemux \
	--enable-libwebpdecoder \
	--enable-swap-16bit-csp \
	--enable-near-lossless \
	--disable-libwebpextras \
	--disable-gl \
	--disable-sdl \
	--disable-png \
	--disable-jpeg \
	--disable-tiff \
	--disable-gif \
	--disable-wic

make
make DESTDIR=$DESTDIR install-strip

find $DESTDIR -type f -name '*.la' -delete

doas chown -R root:root $DESTDIR
doas sh -c "tar -zcC $DESTDIR . | gzip > ../libwebp@$VERSION.tar.gz"
CALLER_UID=$(id -un)
CALLER_GID=$(id -gn)
doas chown -R $CALLER_UID:$CALLER_GID $DESTDIR
