#!/bin/sh -e

bzip2 -cd mtdev-$VERSION.tar.bz2 | tar -x
cd mtdev-$VERSION

./configure --prefix=/usr

make
make DESTDIR="$DESTDIR" install-strip

find $DESTDIR -type f -name '*.la' -delete

su
chown -R root:root $DESTDIR
exit
