#!/bin/sh -e

PRETTY_NAME=nupk
MAJOR=
MINOR=
PATCH=
VERSION=git

mkdir temporary-builddir
DESTDIR="$PWD/temporary-builddir"

git clone https://github.com/Skimmeroni/Nupk.git
install -Dm755 -t "$DESTDIR/usr/bin" nupk.git/nupk

su
chown -R root:root $DESTDIR
tar -zcC $DESTDIR . | gzip > ../nupk@$VERSION.tar.gz
exit
