#!/bin/sh -e

xz -d bison-$VERSION.tar.xz | tar -x
cd bison-$VERSION

./configure \
	--prefix=/usr \
	--disable-nls \
	--without-libtextstyle-prefix

make
make DESTDIR="$DESTDIR" install-strip

rm -rf "$DESTDIR/usr/share/info"
