#!/bin/sh -e

xz -cd bison-$VERSION.tar.xz | tar -x
cd bison-$VERSION

./configure \
	--prefix=/usr \
	--disable-nls \
	--without-libtextstyle-prefix

make
make DESTDIR="$DESTDIR" install-strip

rm -rf "$DESTDIR/usr/share/info"
rm -rf "$DESTDIR/usr/share/doc"
rm -rf "$DESTDIR/usr/share/aclocal"

su
chown -R root:root $DESTDIR
cd $DESTDIR
tar -c * | gzip > ../bison@$VERSION.tar.gz
exit
