#!/bin/sh -e

DEPENDENCIES="m4"
INFO="A general-purpose (yacc-compatible) parser generator"
PRETTY_NAME="bison"
SOURCES="https://ftp.gnu.org/gnu/bison/bison-$VERSION.tar.xz"
MAJOR="3"
MINOR="8"
PATCH="2"
VERSION="$MAJOR.$MINOR.$PATCH"
