#!/bin/sh -e

gzip -cd mpc-$VERSION.tar.gz | tar -x
cd mpc-$VERSION

./configure \
	--prefix=/usr \
	--enable-shared \

make
make DESTDIR="$DESTDIR" install

rm -rf "$DESTDIR/usr/share"
find $DESTDIR -type f -name '*.la' -delete
