#!/bin/sh -e

PRETTY_NAME=libmpc-unclassified
MAJOR=1
MINOR=3
PATCH=1
VERSION=1.3.1

mkdir temporary-builddir
DESTDIR="$PWD/temporary-builddir"

curl --location --remote-name --skip-existing https://ftp.gnu.org/gnu/mpc/mpc-$VERSION.tar.gz

gzip -cd mpc-$VERSION.tar.gz | tar -x
cd mpc-$VERSION

./configure \
	--prefix=/usr \
	--enable-shared

make
make DESTDIR=$DESTDIR install

rm -rf "$DESTDIR/usr/share"
find $DESTDIR -type f -name '*.la' -delete

su
chown -R root:root $DESTDIR
tar -zcC $DESTDIR . | gzip > ../libmpc@$VERSION.tar.gz
exit
