#!/bin/sh -e

gzip -cd mpc-$VERSION.tar.gz | tar -x
cd mpc-$VERSION

./configure \
	--prefix=/usr \
	--enable-shared \

make
make DESTDIR="$DESTDIR" install

rm -rf "$DESTDIR/usr/share"
find $DESTDIR -type f -name '*.la' -delete

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > libmpc@$VERSION.tar.gz
exit
