#!/bin/sh

gzip -cd toybox-$VERSION.tar.gz | tar -x
cd toybox-$VERSION

sed -i 's|egrep|grep -E|g' scripts/*.sh

mv ../configuration .config
make oldconfig
make CFLAGS="$CFLAGS -static" LDFLAGS="$LDFLAGS -static" change

# Hopefully unneeded
rm change/*.bad

for i in $(ls -1 change)
do
	install -Dm755 change/$i "$DESTDIR/usr/bin/$i"
done

su
chown -R root:root $DESTDIR
cd $DESTDIR
tar -c * | gzip > ../toybox@$VERSION.tar.gz
exit
