#!/bin/sh

PRETTY_NAME=toybox
MAJOR=0
MINOR=8
PATCH=12
VERSION=0.8.12

mkdir temporary-builddir
DESTDIR=temporary-builddir

curl --location --remote-name --skip-existing https://landley.net/toybox/downloads/toybox-$VERSION.tar.gz

gzip -cd toybox-$VERSION.tar.gz | tar -x
cd toybox-$VERSION

sed -i 's|egrep|grep -E|g' scripts/*.sh

mv ../configuration .config
make oldconfig
make CFLAGS="$CFLAGS -static" LDFLAGS="$LDFLAGS -static" change

# Hopefully unneeded
rm change/*.bad

for i in $(ls -1 change)
do
	install -Dm755 change/$i "$DESTDIR/usr/bin/$i"
done

su
chown -R root:root $DESTDIR
cd $DESTDIR
tar -c * | gzip > ../toybox@$VERSION.tar.gz
exit
