#!/bin/sh -e

xz -cd wayland-protocols-$VERSION.tar.xz | tar -x
cd wayland-protocols-$VERSION

meson setup \
	-Dprefix=/usr \
	-Ddatadir=lib \
	-Dbuildtype=release \
	-Dtests=false \
	build

meson -C build compile
meson -C build install -d "$DESTDIR"

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > wayland-protocols@$VERSION.tar.gz
exit
