#!/bin/sh -e

tar -xf pixman-$VERSION.tar.xz
cd pixman-$VERSION

muon setup \
	-Dprefix=/usr \
	-Dbuildtype=release \
	-Ddefault_library=both \
	-Dgtk=disabled \
	build

muon -C build samu
muon -C build install -d "$DESTDIR"

find "$DESTDIR/usr/lib" -type f -name '*.a'   -exec strip --strip-unneeded {} \;
find "$DESTDIR/usr/lib" -type f -name '*.so*' -exec strip --strip-unneeded {} \;
