#!/bin/sh -e

PRETTY_NAME=libjpeg-turbo
MAJOR=3
MINOR=1
PATCH=2
VERSION=3.1.2

mkdir temporary-builddir
DESTDIR="$PWD/temporary-builddir"

curl --location --remote-name --skip-existing https://github.com/libjpeg-turbo/libjpeg-turbo/archive/$VERSION.tar.gz

gzip -cd $VERSION.tar.gz | tar -x
cd libjpeg-turbo-$VERSION

cmake -B build \
	-D CMAKE_INSTALL_PREFIX=/usr \
	-D CMAKE_INSTALL_LIBDIR=/usr/lib \
	-D CMAKE_BUILD_TYPE=Release \
	-D ENABLE_STATIC=ON \
	-D ENABLE_SHARED=ON \
	-D WITH_JAVA=OFF \
	-D WITH_TESTS=OFF \
	-D WITH_TOOLS=OFF \
	-G Ninja

cmake --build build
DESTDIR=$DESTDIR cmake --install build --strip

rm -rf $DESTDIR/usr/share

doas chown -R root:root $DESTDIR
doas sh -c "tar -zcC $DESTDIR . | gzip > ../libjpeg-turbo@$VERSION.tar.gz"
