#!/bin/sh -e

tar -xf samurai-$VERSION.tar.gz
cd samurai-$VERSION

make PREFIX=/usr
make PREFIX=/usr DESTDIR="$DESTDIR" install

ln -sf samu   "$DESTDIR/usr/bin/ninja"
ln -sf samu.1 "$DESTDIR/usr/share/man/man1/ninja.1"
