#!/bin/sh -e

PRETTY_NAME=python:mako
MAJOR=1
MINOR=3
PATCH=10
VERSION=1.3.10

mkdir temporary-builddir
DESTDIR="$PWD/temporary-builddir"

curl --location --remote-name --skip-existing https://github.com/sqlalchemy/mako/archive/refs/tags/rel_${MAJOR}_${MINOR}_${PATCH}.tar.gz

gzip -cd rel_${MAJOR}_${MINOR}_${PATCH}.tar.gz | tar -x
cd mako-rel_${MAJOR}_${MINOR}_${PATCH}

gpep517 install-from-source --optimize all --destdir $DESTDIR

find "$DESTDIR/usr/lib" -type f -name '*.so' -exec strip --strip-unneeded {} \;

doas chown -R root:root $DESTDIR
doas sh -c "tar -zcC $DESTDIR . | gzip > ../mako@$VERSION.tar.gz"
