#!/bin/sh -e

PRETTY_NAME=python:mako
MAJOR=1
MINOR=3
PATCH=5
VERSION=1.3.5

mkdir temporary-builddir
DESTDIR="$PWD/temporary-builddir"

curl --location --remote-name --skip-existing https://files.pythonhosted.org/packages/source/M/Mako/Mako-$VERSION.tar.gz

gzip -cd Mako-$VERSION.tar.gz | tar -x
cd Mako-$VERSION

python setup.py build
python setup.py install \
	--prefix=/usr \
	--root="$DESTDIR"

find "$DESTDIR/usr/lib" -type f -name '*.so' -exec strip --strip-unneeded {} \;

su
chown -R root:root $DESTDIR
tar -zcC $DESTDIR . | gzip > ../mako@$VERSION.tar.gz
exit
