#!/bin/sh -e

DEPENDENCIES="python markupsafe"
INFO=""
PRETTY_NAME="python:mako"
SOURCES="https://files.pythonhosted.org/packages/source/M/Mako/Mako-$VERSION.tar.gz"
MAJOR="1"
MINOR="3"
PATCH="5"
VERSION="$MAJOR.$MINOR.$PATCH"
