#!/bin/sh -e

gzip -cd make-$VERSION.tar.gz | tar -x
cd make-$VERSION

export LDFLAGS="$LDFLAGS -static"

./configure \
	--prefix=/usr \
	--disable-nls \
	--without-guile

make
make DESTDIR="$DESTDIR" install-strip

rm -rf "$DESTDIR/usr/share/info"

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > make@$VERSION.tar.gz
exit
