#!/bin/sh -e

xz -cd libarchive-$VERSION.tar.xz | tar -x
cd libarchive-$VERSION

./configure \
	--prefix=/usr \
	--without-openssl \
	--without-expat \
	--without-xml2 \
	--without-lz4 \
	--without-zstd \
	--without-nettle \
	--with-bz2lib \
	--with-zlib \
	--with-lzma \
	--enable-static

make
make DESTDIR="$DESTDIR" install-strip

rm -rf "$DESTDIR/usr/share/man/man3"
find $DESTDIR -type f -name '*.la' -delete

install -Dm644 COPYING "$DESTDIR/usr/share/LICENSES/libarchive.license" 

ln -sf bsdcpio  "$DESTDIR/usr/bin/cpio"
ln -sf bsdtar   "$DESTDIR/usr/bin/tar"
ln -sf bsdunzip "$DESTDIR/usr/bin/unzip"

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > libarchive@$VERSION.tar.gz
exit
