#!/bin/sh -e

DEPENDENCIES="bzip2 xz zlib"
INFO="Multi-format archive and compression library"
PRETTY_NAME="libarchive"
SOURCES="https://libarchive.org/downloads/libarchive-$VERSION.tar.xz"
MAJOR="3"
MINOR="7"
PATCH="7"
VERSION="$MAJOR.$MINOR.$PATCH"
