#!/bin/sh -e

tar -xf $VERSION.tar.gz

mkdir -p "$DESTDIR/usr/share/lua" 
install -Dm755 lua-repl-$VERSION/rep.lua "$DESTDIR/usr/bin/rep.lua" 
cp -r          lua-repl-$VERSION/repl    "$DESTDIR/usr/share/lua"
