#!/bin/sh -e

PRETTY_NAME=sqlite
MAJOR=3
MINOR=45
PATCH=3
VERSION=3.45.3

mkdir temporary-builddir
DESTDIR=temporary-builddir

curl --location --remote-name --skip-existing https://sqlite.org/2024/sqlite-autoconf-$VERSION.tar.gz

gzip -cd sqlite-autoconf-${MAJOR}${MINOR}0${PATCH}00.tar.gz | tar -x
cd sqlite-autoconf-${MAJOR}${MINOR}0${PATCH}00

export CPPFLAGS="$CPPFLAGS -DSQLITE_ENABLE_FTS3"
export CPPFLAGS="$CPPFLAGS -DSQLITE_ENABLE_FTS3_PARENTHESIS"
export CPPFLAGS="$CPPFLAGS -DSQLITE_ENABLE_FTS4"
export CPPFLAGS="$CPPFLAGS -DSQLITE_ENABLE_COLUMN_METADATA"

./configure \
	--prefix=/usr \
	--enable-dynamic-extensions \
	--enable-editline \
	--enable-fts5 \
	--enable-threadsafe \
	--disable-debug \
	--disable-readline

make
make DESTDIR="$DESTDIR" install-strip

find $DESTDIR -type f -name '*.la' -delete

su
chown -R root:root $DESTDIR
tar -c -C $DESTDIR . | gzip > ../sqlite@$VERSION.tar.gz
exit
