#!/bin/sh -e

DEPENDENCIES="zlib libedit"
INFO=""
PRETTY_NAME="sqlite"
SOURCES="https://sqlite.org/2024/sqlite-autoconf-$MAJOR$MINOR0$PATCH00.tar.gz"
MAJOR="3"
MINOR="45"
PATCH="3"
VERSION="$MAJOR.$MINOR.$PATCH"
