#!/bin/sh -e

gzip -cd $VERSION.tar.gz | tar -x
cd meson-$VERSION

python setup.py build
python setup.py install \
    --root="$DESTDIR" \
    --optimize=1 \
    --skip-build

rm -rf "$DESTDIR/usr/share/polkit-1"
