#!/bin/sh -e

PRETTY_NAME=meson
MAJOR=1
MINOR=2
PATCH=3
VERSION=1.2.3

mkdir temporary-builddir
DESTDIR="$PWD/temporary-builddir"

curl --location --remote-name --skip-existing https://github.com/mesonbuild/meson/archive/.tar.gz
gzip -cd $VERSION.tar.gz | tar -x
cd meson-$VERSION

python setup.py build
python setup.py install \
    --root="$DESTDIR" \
    --optimize=1 \
    --skip-build

rm -rf "$DESTDIR/usr/share/polkit-1"

doas chown -R root:root $DESTDIR
doas sh -c "tar -zcC $DESTDIR . | gzip > ../meson@$VERSION.tar.gz"
