#!/bin/sh -e

DEPENDENCIES="python samurai"
INFO="Open source build system"
PRETTY_NAME="meson"
SOURCES="https://github.com/mesonbuild/meson/archive/$VERSION.tar.gz"
MAJOR="1"
MINOR="2"
PATCH="3"
VERSION="$MAJOR.$MINOR.$PATCH"
