#!/bin/sh -e

PRETTY_NAME=pixman
MAJOR=0
MINOR=43
PATCH=4
VERSION=0.43.4

mkdir temporary-builddir
DESTDIR=temporary-builddir

curl --location --remote-name --skip-existing https://x.org/releases/individual/lib/pixman-$VERSION.tar.xz

xz -cd pixman-$VERSION.tar.xz | tar -x
cd pixman-$VERSION

meson setup \
	-Dprefix=/usr \
	-Dbuildtype=release \
	-Ddefault_library=both \
	-Dgtk=disabled \
	-Dtest=disabled \
	-Dlibpng=disabled \
	-Ddemos=disabled \
	build

meson -C build compile
meson -C build install -d "$DESTDIR"

find "$DESTDIR/usr/lib" -type f -name '*.a'   -exec strip --strip-unneeded {} \;
find "$DESTDIR/usr/lib" -type f -name '*.so*' -exec strip --strip-unneeded {} \;

su
chown -R root:root $DESTDIR
cd $DESTDIR
tar -c * | gzip > ../pixman@$VERSION.tar.gz
exit
