#!/bin/sh -e

tar -xf curl-$VERSION.tar.xz
cd curl-$VERSION

./configure \
	--prefix=/usr \
	--enable-ipv6 \
	--enable-unix-sockets \
	--enable-symbol-hiding \
	--disable-manual \
	--disable-ldap \
	--disable-ares \
	--with-openssl \
	--with-pic \
	--with-ca-fallback \
	--without-librtmp \
	--without-libpsl \
	--without-libidn2 \
	--without-brotli \
	--without-zstd

make
make DESTDIR="$DESTDIR" install

rm -rf "$DESTDIR/usr/share/man/man3"
rm -rf "$DESTDIR/usr/share/aclocal"

find $DESTDIR -type f -name '*.la' -delete
