#!/bin/sh -e

tar -xf libarchive-$VERSION.tar.xz
cd libarchive-$VERSION

./configure \
	--prefix=/usr \
	--without-openssl \
	--without-expat \
	--without-xml2 \
	--without-lz4 \
	--without-zstd \
	--without-nettle \
	--with-bz2lib \
	--with-zlib \
	--with-lzma \
	--enable-static

make
make DESTDIR="$DESTDIR" install

rm -rf "$DESTDIR/usr/share/man/man3"
find $DESTDIR -type f -name '*.la' -delete

install -Dm644 COPYING "$DESTDIR/usr/share/LICENSES/libarchive.license" 

ln -s bsdcpio  "$DESTDIR/usr/bin/cpio"
ln -s bsdtar   "$DESTDIR/usr/bin/tar"
ln -s bsdunzip "$DESTDIR/usr/bin/unzip"
