#!/bin/sh -e

PRETTY_NAME=scdoc
MAJOR=1
MINOR=11
PATCH=3
VERSION=1.11.3

mkdir temporary-builddir
DESTDIR=temporary-builddir

curl --location --remote-name --skip-existing https://git.sr.ht/~sircmpwn/scdoc/archive/.tar.gz
gzip -cd $VERSION.tar.gz | tar -x
cd scdoc-$VERSION

make PREFIX=/usr
make PREFIX=/usr PCDIR=/usr/lib/pkgconfig install

strip --strip-unneeded "$DESTDIR/usr/bin/scdoc"

su
chown -R root:root $DESTDIR
tar -c -C $DESTDIR . | gzip > ../scdoc@$VERSION.tar.gz
exit
