#!/bin/sh -e

PRETTY_NAME=scdoc
MAJOR=1
MINOR=11
PATCH=3
VERSION=1.11.3

mkdir temporary-builddir
DESTDIR="$PWD/temporary-builddir"

curl --location --remote-name --skip-existing https://git.sr.ht/~sircmpwn/scdoc/archive/$VERSION.tar.gz

gzip -cd $VERSION.tar.gz | tar -x
cd scdoc-$VERSION

make PREFIX=/usr PCDIR=/usr/lib/pkgconfig
make PREFIX=/usr PCDIR=/usr/lib/pkgconfig DESTDIR=$DESTDIR install

strip --strip-unneeded "$DESTDIR/usr/bin/scdoc"

doas chown -R root:root $DESTDIR
doas sh -c "tar -zcC $DESTDIR . | gzip > ../scdoc@$VERSION.tar.gz"
