#!/bin/sh -e

gzip -cd $VERSION.tar.gz | tar -x
cd scdoc-$VERSION

make PREFIX=/usr
make PREFIX=/usr PCDIR=/usr/lib/pkgconfig install

strip --strip-unneeded "$DESTDIR/usr/bin/scdoc"

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > scdoc@$VERSION.tar.gz
exit
