#!/bin/sh -e

tar -xf v$VERSION.tar.gz
cd ccore-$VERSION/src/openbsd/diff
cp ../compat.h .

for i in $(ls *.c)
do
	$CC -c $i
done

$CC -static diff.c *.o -o diff

install -Dm755 -t "$DESTDIR/usr/bin" diff
install -Dm644 -t "$DESTDIR/usr/share/man/man1" diff.1
