#!/bin/sh -e

tar -xf $VERSION.tar.gz
cd muon-$VERSION

./bootstrap.sh build

build/muon setup -Dprefix=/usr build
build/muon -C build samu
build/muon -C build install -d "$DESTDIR"

strip --strip-unneeded "$DESTDIR/usr/bin/muon"
