#!/bin/sh -e

PRETTY_NAME=fontconfig
MAJOR=2
MINOR=17
PATCH=1
VERSION=2.17.1

mkdir temporary-distdir
DESTDIR="$PWD/temporary-distdir"

curl --location --remote-name --skip-existing https://gitlab.freedesktop.org/api/v4/projects/890/packages/generic/fontconfig/$VERSION/fontconfig-$VERSION.tar.xz

xz -cd fontconfig-$VERSION.tar.xz | tar -x
cd fontconfig-$VERSION

./configure \
	--prefix=/usr \
	--localstatedir=/var \
	--sysconfdir=/etc \
	--enable-static \
	--enable-shared \
	--disable-docs \
	--disable-nls

make
make DESTDIR=$DESTDIR install-strip

mkdir -p $DESTDIR/usr/share/man/man1
install -m644 fc-*/*.1 $DESTDIR/usr/share/man/man1

find $DESTDIR -type f -name '*.la' -delete

doas chown -R root:root $DESTDIR
doas sh -c "tar -zcC $DESTDIR . | gzip > ../fontconfig@$VERSION.tar.gz"
CALLER_UID=$(id -un)
CALLER_GID=$(id -gn)
doas chown -R $CALLER_UID:$CALLER_GID $DESTDIR
