#!/bin/sh -e

PRETTY_NAME=oksh
MAJOR=7
MINOR=7
PATCH=
VERSION=7.7

mkdir temporary-builddir
DESTDIR=temporary-builddir

curl --location --remote-name --skip-existing https://github.com/ibara/oksh/releases/download/oksh-/oksh-$VERSION.tar.gz

gzip -cd oksh-$VERSION.tar.gz | tar -x
cd oksh-$VERSION

./configure \
	--prefix=/usr \
	--bindir=/usr/bin \
	--mandir=/usr/share/man \
	--enable-curses \
	--enable-static \
	--strip

make
make DESTDIR=$DESTDIR install

ln -sf oksh "$DESTDIR/usr/bin/sh"

su
chown -R root:root $DESTDIR
tar -c -C $DESTDIR . | gzip > ../oksh@$VERSION.tar.gz
exit
