#!/bin/sh -e

gzip -cd oksh-$VERSION.tar.gz | tar -x
cd oksh-$VERSION

./configure \
	--prefix=/usr \
	--bindir=/usr/bin \
	--mandir=/usr/share/man \
	--disable-curses \
	--enable-static \
	--strip

make
make DESTDIR="$DESTDIR" install

ln -sf oksh "$DESTDIR/usr/bin/sh"

su
chown -R root:root $DESTDIR
cd $DESTDIR
tar -c * | gzip > ../oksh@$VERSION.tar.gz
exit
