#!/bin/sh -e

gzip -d libedit-$VERSION.tar.gz | tar -x
cd libedit-$VERSION

patch -p1 < ../fix-missing-header.patch

./configure \
	--prefix=/usr \
	--enable-static \
	--enable-fast-install

make
make install

find $DESTDIR -type f -name '*.la' -delete
rm -rf "$DESTDIR/usr/share/man/man3"
