#!/bin/sh -e

PRETTY_NAME=libedit
MAJOR=20230828-3
MINOR=1
PATCH=
VERSION=20230828-3.1

mkdir temporary-builddir
DESTDIR=temporary-builddir

curl --location --remote-name --skip-existing https://www.thrysoee.dk/editline/libedit-$VERSION.tar.gz

gzip -cd libedit-$VERSION.tar.gz | tar -x
cd libedit-$VERSION

patch -p1 < ../fix-missing-header.patch

./configure \
	--prefix=/usr \
	--enable-static \
	--enable-fast-install

make
make install

find $DESTDIR -type f -name '*.la' -delete
rm -rf "$DESTDIR/usr/share/man/man3"

su
chown -R root:root $DESTDIR
cd $DESTDIR
tar -c * | gzip > ../libedit@$VERSION.tar.gz
exit
