#!/bin/sh -e

tar -xf v$VERSION.tar.gz
cd luafilesystem-$VERSION

export CFLAGS="$CFLAGS -pedantic"

$CC $CFLAGS -o src/lfs.out -c src/lfs.c
$AR rcs src/lfs.a src/lfs.out
$CC -shared -llua $LDFLAGS -o src/lfs.so src/lfs.out

install -Dm644 src/lfs.so "$DESTDIR/usr/lib/lua/lfs.so"
install -Dm644 src/lfs.a  "$DESTDIR/usr/lib/lua/lfs.a"

install -Dm644 LICENSE "$DESTDIR/usr/share/LICENSES/lua-filesystem.license"
