#!/bin/sh -e

DEPENDENCIES="lua"
INFO=""
PRETTY_NAME="lua-filesystem"
SOURCES="https://github.com/lunarmodules/luafilesystem/archive/refs/tags/v$VERSION.tar.gz"
MAJOR="1"
MINOR="8"
PATCH="0"
VERSION="$MAJOR_$MINOR_$PATCH"
