#!/bin/sh -e

PRETTY_NAME=lynx
MAJOR=2
MINOR=9
PATCH=2
VERSION=2.9.2

mkdir temporary-builddir
DESTDIR="$PWD/temporary-builddir"

curl --location --remote-name --skip-existing https://invisible-mirror.net/archives/lynx/tarballs/lynx$VERSION.tar.bz2

bzip2 -cd lynx$VERSION.tar.bz2 | tar -x
cd lynx$VERSION

./configure \
	--prefix=/usr \
	--sysconfdir=/etc/lynx \
	--with-bzlib \
	--with-ssl \
	--with-zlib

make
make DESTDIR=$DESTDIR install

strip --strip-unneeded $DESTDIR/usr/bin/lynx

doas chown -R root:root $DESTDIR
doas sh -c "tar -zcC $DESTDIR . | gzip > ../lynx@$VERSION.tar.gz"
