#!/bin/sh -e

gzip -cd file-$VERSION.tar.gz | tar -x
cd file-$VERSION

./configure \
	--prefix=/usr \
	--enable-fsect-man5 \
	--enable-static \
	--enable-zlib \
	--disable-bzlib \
	--disable-xzlib \
	--disable-libseccomp

make
make install-strip

rm -rf "$DESTDIR/usr/share/man/man3"
find $DESTDIR -type f -name '*.la' -delete

su
chown -R root:root $DESTDIR
exit
