#!/bin/sh -e

PRETTY_NAME=file
MAJOR=5
MINOR=45
PATCH=
VERSION=5.45

mkdir temporary-builddir
DESTDIR="$PWD/temporary-builddir"

curl --location --remote-name --skip-existing https://astron.com/pub/file/file-$VERSION.tar.gz

gzip -cd file-$VERSION.tar.gz | tar -x
cd file-$VERSION

./configure \
	--prefix=/usr \
	--enable-fsect-man5 \
	--enable-static \
	--enable-zlib \
	--disable-bzlib \
	--disable-xzlib \
	--disable-libseccomp

make
make install-strip

rm -rf "$DESTDIR/usr/share/man/man3"
find $DESTDIR -type f -name '*.la' -delete

doas chown -R root:root $DESTDIR
doas sh -c "tar -zcC $DESTDIR . | gzip > ../file@$VERSION.tar.gz"
