#!/bin/sh -e

DEPENDENCIES="zlib"
INFO="Identify a file's format by scanning binary data for patterns"
PRETTY_NAME="file"
SOURCES="https://astron.com/pub/file/file-$VERSION.tar.gz"
MAJOR="5"
MINOR="45"
VERSION="$MAJOR.$MINOR"
