#!/bin/sh -e

PRETTY_NAME=xkeyboard-config
MAJOR=2
MINOR=41
PATCH=
VERSION=2.41

mkdir temporary-builddir
DESTDIR="$PWD/temporary-builddir"

curl --location --remote-name --skip-existing https://x.org/releases/individual/data/xkeyboard-config/xkeyboard-config-$VERSION.tar.xz

xz -cd xkeyboard-config-$VERSION.tar.xz | tar -x
cd xkeyboard-config-$VERSION

sed -i "s/subdir('po')//g" meson.build

meson setup \
	-Dprefix=/usr \
	-Dbuildtype=release \
	-Dxkb-base=/usr/share/X11/xkb \
	-Dcompat-rules=true \
	build

meson -C build compile
meson -C build install -d "$DESTDIR"

mkdir -p "$DESTDIR/usr/lib"
mv "$DESTDIR/usr/share/pkgconfig" "$DESTDIR/usr/lib/pkgconfig"

su
chown -R root:root $DESTDIR
tar -zcC $DESTDIR . | gzip > ../xkeyboard-config@$VERSION.tar.gz
exit
