#!/bin/sh -e

xz -cd xkeyboard-config-$VERSION.tar.xz | tar -x
cd xkeyboard-config-$VERSION

sed -i "s/subdir('po')//g" meson.build

meson setup \
	-Dprefix=/usr \
	-Dbuildtype=release \
	-Dxkb-base=/usr/share/X11/xkb \
	-Dcompat-rules=true \
	build

meson -C build compile
meson -C build install -d "$DESTDIR"

mkdir -p "$DESTDIR/usr/lib"
mv "$DESTDIR/usr/share/pkgconfig" "$DESTDIR/usr/lib/pkgconfig"

su
chown -R root:root $DESTDIR
exit
