#!/bin/sh -e

gzip -cd bc-$VERSION.tar.gz | tar -x
cd bc-$VERSION

./configure \
	--prefix=/usr \
	--enable-editline \
	--disable-generated-tests \
	--disable-nls \
	--disable-problematic-tests

make
make install

find "$DESTDIR/usr/bin" -type f -exec strip --strip-unneeded {} \;

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > bc@$VERSION.tar.gz
exit
