#!/bin/sh -e

PRETTY_NAME=bc-gh
MAJOR=6
MINOR=7
PATCH=5
VERSION=6.7.5

mkdir temporary-builddir
DESTDIR=temporary-builddir

curl --location --remote-name --skip-existing https://github.com/gavinhoward/bc/releases/download//bc-$VERSION.tar.gz

gzip -cd bc-$VERSION.tar.gz | tar -x
cd bc-$VERSION

./configure \
	--prefix=/usr \
	--enable-editline \
	--disable-generated-tests \
	--disable-nls \
	--disable-problematic-tests

make
make install

find "$DESTDIR/usr/bin" -type f -exec strip --strip-unneeded {} \;

su
chown -R root:root $DESTDIR
cd $DESTDIR
tar -c * | gzip > ../bc@$VERSION.tar.gz
exit
