#!/bin/sh -e

gzip -cd flex-$VERSION.tar.gz | tar -x
cd flex-$VERSION

./configure \
	--prefix=/usr \
	ac_cv_func_malloc_0_nonnull=yes \
	ac_cv_func_realloc_0_nonnull=yes

make
make DESTDIR="$DESTDIR" install-strip

ln -sf flex "$DESTDIR/usr/bin/lex"

rm -rf "$DESTDIR/usr/share/doc"
rm -rf "$DESTDIR/usr/share/info"

find $DESTDIR -type f -name '*.la' -delete

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > flex@$VERSION.tar.gz
exit
