#!/bin/sh -e

PRETTY_NAME=flex
MAJOR=2
MINOR=6
PATCH=4
VERSION=2.6.4

mkdir temporary-builddir
DESTDIR=temporary-builddir

curl --location --remote-name --skip-existing https://github.com/westes/flex/releases/download/v/flex-$VERSION.tar.gz

gzip -cd flex-$VERSION.tar.gz | tar -x
cd flex-$VERSION

./configure \
	--prefix=/usr \
	ac_cv_func_malloc_0_nonnull=yes \
	ac_cv_func_realloc_0_nonnull=yes

make
make DESTDIR="$DESTDIR" install-strip

ln -sf flex "$DESTDIR/usr/bin/lex"

rm -rf "$DESTDIR/usr/share/doc"
rm -rf "$DESTDIR/usr/share/info"

find $DESTDIR -type f -name '*.la' -delete

su
chown -R root:root $DESTDIR
tar -c -C $DESTDIR . | gzip > ../flex@$VERSION.tar.gz
exit
