#!/bin/sh -e

PRETTY_NAME=flex
MAJOR=2
MINOR=6
PATCH=4
VERSION=2.6.4

if [ ! -f $0 ]; then return; fi

mkdir temporary-distdir
DESTDIR="$PWD/temporary-distdir"

curl --location --remote-name --skip-existing https://github.com/westes/flex/releases/download/v/flex-$VERSION.tar.gz

gzip -cd flex-$VERSION.tar.gz | tar -x
cd flex-$VERSION

./configure \
	--prefix=/usr \
	ac_cv_func_malloc_0_nonnull=yes \
	ac_cv_func_realloc_0_nonnull=yes

make
make DESTDIR=$DESTDIR install-strip

ln -sf flex "$DESTDIR/usr/bin/lex"

rm -rf "$DESTDIR/usr/share/doc"
rm -rf "$DESTDIR/usr/share/info"

find $DESTDIR -type f -name '*.la' -delete

doas chown -R root:root $DESTDIR
doas sh -c "tar -zcC $DESTDIR . | gzip > ../flex@$VERSION.tar.gz"
CALLER_UID=$(id -un)
CALLER_GID=$(id -gn)
doas chown -R $CALLER_UID:$CALLER_GID $DESTDIR
