#!/bin/sh -e

DEPENDENCIES="m4"
INFO="The Fast Lexical Analyzer"
PRETTY_NAME="flex"
SOURCES="https://github.com/westes/flex/releases/download/v$VERSION/flex-$VERSION.tar.gz"
MAJOR="2"
MINOR="6"
PATCH="4"
VERSION="$MAJOR.$MINOR.$PATCH"
