#!/bin/sh -e

tar -xf sed-$VERSION.tar.xz
cd sed-$VERSION

export CFLAGS="$CFLAGS -static"

./configure \
	--prefix=/usr \
	--enable-threads=posix \
	--disable-acl \
	--disable-nls \
	--disable-i18n \
	--without-selinux \
	--without-packager

make
make DESTDIR="$DESTDIR" install-strip

rm -rf "$DESTDIR/usr/share/info"
