#!/bin/sh -e

DEPENDENCIES="bzip2 expat libedit libffi libressl sqlite tzdata zlib"
INFO="An interpreted, interactive, object-oriented programming language"
PRETTY_NAME="python3"
SOURCES="https://www.python.org/ftp/python/$VERSION/Python-$VERSION.tar.xz"
MAJOR="3"
MINOR="12"
PATCH="2"
VERSION="$MAJOR.$MINOR.$PATCH"
