#!/bin/sh -e

gzip -d skalibs-$VERSION.tar.gz | tar -x
cd skalibs-$VERSION

./configure \
	--prefix=/usr \
	--with-sysdep-devurandom=yes

make
make DESTDIR="$DESTDIR" install

find $DESTDIR -name '*.a'   -type f -exec strip --strip-unneeded {} \;
find $DESTDIR -name '*.so*' -type f -exec strip --strip-unneeded {} \;
