#!/bin/sh -e

PRETTY_NAME=skalibs
MAJOR=2
MINOR=14
PATCH=3
VERSION=2.14.3.0

mkdir temporary-builddir
DESTDIR="$PWD/temporary-builddir"

curl --location --remote-name --skip-existing https://www.skarnet.org/software/skalibs/skalibs-$VERSION.tar.gz

gzip -cd skalibs-$VERSION.tar.gz | tar -x
cd skalibs-$VERSION

./configure \
	--prefix=/usr \
	--with-sysdep-devurandom=yes

make
make DESTDIR=$DESTDIR install

find $DESTDIR -name '*.a'   -type f -exec strip --strip-unneeded {} \;
find $DESTDIR -name '*.so*' -type f -exec strip --strip-unneeded {} \;

su
chown -R root:root $DESTDIR
tar -zcC $DESTDIR . | gzip > ../skalibs@$VERSION.tar.gz
exit
