#!/bin/sh -e

DEPENDENCIES=""
INFO="General-purpose libraries from skarnet.org"
PRETTY_NAME="skalibs"
SOURCES="https://www.skarnet.org/software/skalibs/skalibs-$VERSION.tar.gz"
MAJOR="2"
MINOR="14"
PATCH="1"
VERSION="$MAJOR.$MINOR.$PATCH"
