#!/bin/sh -e

tar -xf gmp-$VERSION.tar.xz
cd gmp-$VERSION

./configure \
	--prefix=/usr \
	--localstatedir=/var/state/gmp \
	--enable-cxx \
	--enable-fat \
	--with-pic

make
make DESTDIR="$DESTDIR" install

rm -rf "$DESTDIR/usr/share"
find $DESTDIR -type f -name '*.la' -delete
