#!/bin/sh -e

tar -xf Mako-$VERSION.tar.gz
cd Mako-$VERSION

python setup.py build
python setup.py install \
	--prefix=/usr \
	--root="$DESTDIR"

find "$DESTDIR/usr/lib" -type f -name '*.so' -exec strip --strip-unneeded {} \;
