#!/bin/sh -e

tar -xf mpfr-$VERSION.tar.xz
cd mpfr-$VERSION

./configure \
	--prefix=/usr \
	--enable-shared \
	--enable-thread-safe

make
make DESTDIR="$DESTDIR" install

rm -rf "$DESTDIR/usr/share"
find $DESTDIR -type f -name '*.la' -delete
