#!/bin/sh -e

gzip -cd v$VERSION.tar.gz | tar -x
cd netbsd-curses-$VERSION

make PREFIX=/usr all
make PREFIX=/usr DESTDIR="$DESTDIR" install

ln -sf libterminfo.so "$DESTDIR/usr/lib/libtinfo.so"
ln -sf libterminfo.a  "$DESTDIR/usr/lib/libtinfo.a"

rm -rf "$DESTDIR/usr/share/man/man3"

find "$DESTDIR/usr/bin"       -type f -exec strip --strip-unneeded {} \;
find "$DESTDIR" -name '*.a'   -type f -exec strip --strip-unneeded {} \;
find "$DESTDIR" -name '*.so*' -type f -exec strip --strip-unneeded {} \;

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > ncurses@$VERSION.tar.gz
exit
