#!/bin/sh -e

DEPENDENCIES=""
INFO="Console display library"
PRETTY_NAME="netbsd-curses"
SOURCES="https://github.com/sabotage-linux/netbsd-curses/archive/refs/tags/v$VERSION.tar.gz"
MAJOR="0"
MINOR="3"
PATCH="2"
VERSION="$MAJOR.$MINOR.$PATCH"
