#!/bin/sh -e

DEPENDENCIES="lua"
INFO=""
PRETTY_NAME="lua-utf8"
SOURCES="https://github.com/starwing/luautf8/archive/refs/tags/$VERSION.tar.gz"
MAJOR="0"
MINOR="1"
PATCH="5"
VERSION="$MAJOR.$MINOR.$PATCH"
