#!/bin/sh -e

DEPENDENCIES="zlib"
INFO="The Perl language"
PRETTY_NAME="perl"
SOURCES="https://www.cpan.org/src/$MAJOR.0/perl-$VERSION.tar.gz"
MAJOR="5"
MINOR="36"
PATCH="3"
VERSION="$MAJOR.$MINOR.$PATCH"
