#!/bin/sh -e

DEPENDENCIES="lua"
INFO=""
PRETTY_NAME="vstruct"
SOURCES="https://github.com/ToxicFrog/vstruct/archive/refs/tags/v$VERSION.tar.gz"
MAJOR="2"
MINOR="1"
PATCH="1"
VERSION="$MAJOR.$MINOR.$PATCH"
