#!/bin/sh -e

tar -xf wayland-$VERSION.tar.xz
cd wayland-$VERSION

muon setup \
	-Dprefix=/usr \
	-Dbuildtype=release \
	-Ddefault_library=both \
	-Dtests=false \
	-Ddocumentation=false \
	-Ddtd_validation=false \
	build

muon -C build samu
muon -C build install -d "$DESTDIR"

find "$DESTDIR/usr/lib" -type f -name '*.a'   -exec strip --strip-unneeded {} \;
find "$DESTDIR/usr/lib" -type f -name '*.so*' -exec strip --strip-unneeded {} \;
strip --strip-unneeded "$DESTDIR/usr/bin/wayland-scanner"
