#!/bin/sh -e

tar -xf TwitterColorEmoji-SVGinOT-Linux-$VERSION.tar.gz
cd TwitterColorEmoji-SVGinOT-Linux-$VERSION

install -Dm644 -t "$DESTDIR/usr/share/fonts/TTF" TwitterColorEmoji-SVGinOT.ttf
install -Dm644 LICENSE-CC-BY.txt "$DESTDIR/usr/share/LICENSES/ttf-twemoji-color.license"
