#!/bin/sh -e

PRETTY_NAME=fonts:twemoji-color
MAJOR=14
MINOR=0
PATCH=2
VERSION=14.0.2

mkdir temporary-builddir
DESTDIR=temporary-builddir

curl --location --remote-name --skip-existing https://github.com/13rac1/twemoji-color-font/releases/download/v/TwitterColorEmoji-SVGinOT-Linux-$VERSION.tar.gz

gzip TwitterColorEmoji-SVGinOT-Linux-$VERSION.tar.gz | tar -x
cd TwitterColorEmoji-SVGinOT-Linux-$VERSION

install -Dm644 -t "$DESTDIR/usr/share/fonts/TTF" TwitterColorEmoji-SVGinOT.ttf
install -Dm644 LICENSE-CC-BY.txt "$DESTDIR/usr/share/LICENSES/ttf-twemoji-color.license"

su
chown -R root:root $DESTDIR
cd $DESTDIR
tar -c * | gzip > ../ttf-twemoji-color@$VERSION.tar.gz
exit
