#!/bin/sh -e

gzip TwitterColorEmoji-SVGinOT-Linux-$VERSION.tar.gz | tar -x
cd TwitterColorEmoji-SVGinOT-Linux-$VERSION

install -Dm644 -t "$DESTDIR/usr/share/fonts/TTF" TwitterColorEmoji-SVGinOT.ttf
install -Dm644 LICENSE-CC-BY.txt "$DESTDIR/usr/share/LICENSES/ttf-twemoji-color.license"

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > ttf-twemoji-color@$VERSION.tar.gz
exit
