#!/bin/sh -e

DEPENDENCIES="lua"
INFO=""
PRETTY_NAME="lua-stdlib"
SOURCES="https://github.com/lua-stdlib/lua-stdlib/archive/refs/tags/release-v$VERSION.tar.gz"
MAJOR="41"
MINOR="2"
PATCH="2"
VERSION="$MAJOR.$MINOR.$PATCH"
