#!/bin/sh -e

tar -xf libressl-$VERSION.tar.gz
cd libressl-$VERSION

./configure \
	--prefix=/usr \
	--enable-static \
	--disable-tests

make
make DESTDIR="$DESTDIR" install-strip

rm -rf "$DESTDIR/usr/share/man"
install -Dm644 COPYING "$DESTDIR/usr/share/LICENSES/libressl.license"
