#!/bin/sh -e

tar -xf dash-$VERSION.tar.gz
cd dash-$VERSION

./configure \
	--prefix=/usr \
	--bindir=/usr/bin \
	--mandir=/usr/share/man \
	--enable-static \
	--without-libedit

make
make DESTDIR="$DESTDIR" install-strip

ln -sf dash "$DESTDIR/usr/bin/sh"
