#!/bin/sh -e

gzip -cd $VERSION.tar.gz | tar -x
cd muon-$VERSION

./bootstrap.sh build

build/meson setup -Dprefix=/usr build
build/meson -C build compile
build/meson -C build install -d "$DESTDIR"

strip --strip-unneeded "$DESTDIR/usr/bin/muon"

su
chown -R root:root $DESTDIR
cd $DESTDIR
tar -c * | gzip > ../muon@$VERSION.tar.gz
exit
