#!/bin/sh -e

gzip -d $VERSION.tar.gz | tar -x
cd muon-$VERSION

./bootstrap.sh build

build/meson setup -Dprefix=/usr build
build/meson -C build compile
build/meson -C build install -d "$DESTDIR"

strip --strip-unneeded "$DESTDIR/usr/bin/muon"
