#!/bin/sh -e

PRETTY_NAME=muon
MAJOR=
MINOR=
PATCH=
VERSION=git

mkdir temporary-builddir
DESTDIR="$PWD/temporary-builddir"

curl --location --remote-name --skip-existing https://git.sr.ht/~lattis/muon
gzip -cd $VERSION.tar.gz | tar -x
cd muon-$VERSION

./bootstrap.sh build

build/meson setup -Dprefix=/usr build
build/meson -C build compile
build/meson -C build install -d "$DESTDIR"

strip --strip-unneeded "$DESTDIR/usr/bin/muon"

doas chown -R root:root $DESTDIR
doas sh -c "tar -zcC $DESTDIR . | gzip > ../muon@$VERSION.tar.gz"
