#!/bin/sh -e

mkdir -p "$DESTDIR/usr/bin" 
$CC $CFLAGS getent.c   -o "$DESTDIR/usr/bin/getent" 
$CC $CFLAGS getconf.c  -o "$DESTDIR/usr/bin/getconf"

strip --strip-unneeded "$DESTDIR/usr/bin/getent"
strip --strip-unneeded "$DESTDIR/usr/bin/getconf"

install -Dm755 cdefs.h "$DESTDIR/usr/include/sys/cdefs.h"
install -Dm755 queue.h "$DESTDIR/usr/include/sys/queue.h"
install -Dm755 tree.h  "$DESTDIR/usr/include/sys/tree.h"

tar -xf musl-$VERSION.tar.gz
cd musl-$VERSION

./configure \
	--prefix=/usr \
	--syslibdir=/usr/lib

make
make DESTDIR="$DESTDIR" install-strip

ln -sf /usr/lib/ld-musl-armhf.so.1 "$DESTDIR/usr/bin/ldd"
ln -sf libc.so "$DESTDIR/usr/lib/ld-musl-armhf.so.1"
