#!/bin/sh -e

gzip -cd zlib-$VERSION.tar.gz | tar -x
cd zlib-$VERSION

./configure --prefix=/usr

make
make DESTDIR="$DESTDIR" install

find $DESTDIR -name '*.a'   -type f -exec strip --strip-unneeded {} \;
find $DESTDIR -name '*.so*' -type f -exec strip --strip-unneeded {} \;

rm -rf "$DESTDIR/usr/share"
find $DESTDIR -type f -name '*.la' -delete

su
chown -R root:root $DESTDIR
exit
