#!/bin/sh -e

DEPENDENCIES=""
INFO="Standard (de)compression library"
PRETTY_NAME="zlib"
SOURCES="https://zlib.net/fossils/zlib-$VERSION.tar.gz"
MAJOR="1"
MINOR="3"
PATCH="1"
VERSION="$MAJOR.$MINOR.$PATCH"
