#!/bin/sh -e

DEPENDENCIES=""
INFO="Compare files and apply patches"
PRETTY_NAME="diffutils"
SOURCES="https://landley.net/toybox/downloads/toybox-$VERSION.tar.gz"
MAJOR="0"
MINOR="8"
PATCH="12"
VERSION="$MAJOR.$MINOR.$PATCH"
