#!/bin/sh -e

cd ubase.git

# Redundant
sed -i 's|dd\\|\\|g' Makefile
sed -i 's|dd\.1\\|\\|g' Makefile
sed -i 's|mknod\\|\\|g' Makefile
sed -i 's|mknod\.1\\|\\|g' Makefile
sed -i 's|clear\\|\\|g' Makefile
sed -i 's|clear\.1\\|\\|g' Makefile

make \
	PREFIX=/usr \
	CFLAGS="$CFLAGS -static" \
	LDFLAGS="$LDFLAGS -static" 
 
make \
	PREFIX=/usr \
	CFLAGS="$CFLAGS -static" \
	LDFLAGS="$LDFLAGS -static" \
	DESTDIR="$DESTDIR" \
	install

find "$DESTDIR/usr/bin" -type f -exec strip --strip-unneeded {} \;

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > ubase@$VERSION.tar.gz
exit
