#!/bin/sh -e

cd ubase.git

make \
	PREFIX=/usr \
	CFLAGS="$CFLAGS -static" \
	LDFLAGS="$LDFLAGS -static" 
 
make \
	PREFIX=/usr \
	CFLAGS="$CFLAGS -static" \
	LDFLAGS="$LDFLAGS -static" \
	DESTDIR="$DESTDIR" \
	install

# dd and mknod already present in sbase

rm "$DESTDIR/usr/bin/dd"
rm "$DESTDIR/usr/bin/mknod"
rm "$DESTDIR/usr/share/man/man1/dd.1"
rm "$DESTDIR/usr/share/man/man1/mknod.1"

find "$DESTDIR/usr/bin" -type f -exec strip --strip-unneeded {} \;

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > ubase@$VERSION.tar.gz
exit
