#!/bin/sh -e

tar -xf libevdev-$VERSION.tar.xz
cd libevdev-$VERSION

./configure --prefix=/usr

make
make DESTDIR="$DESTDIR" install-strip

rm -rf "$DESTDIR/usr/share/man/man3"
find $DESTDIR -type f -name '*.la' -delete
