#!/bin/sh -e

gzip -cd v$VERSION.tar.gz | tar -x
cd setuptools-$VERSION

# Useful trick for boostrapping setuptools
mkdir -p "build/scripts-3.$(python -c "print(__import__('sys').version_info[1])")"

python setup.py build
python setup.py install \
	--prefix=/usr \
	--root="$DESTDIR"

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > setuptools@$VERSION.tar.gz
exit
