#!/bin/sh -e

gzip -d v$VERSION.tar.gz | tar -x
cd setuptools-$VERSION

# Useful trick for boostrapping setuptools
mkdir -p "build/scripts-3.$(python -c "print(__import__('sys').version_info[1])")"

python setup.py build
python setup.py install \
	--prefix=/usr \
	--root="$DESTDIR"
