#!/bin/sh -e

DEPENDENCIES="python"
INFO=""
PRETTY_NAME="python-setuptools"
SOURCES="https://github.com/pypa/setuptools/archive/refs/tags/v$VERSION.tar.gz"
MAJOR="70"
MINOR="0"
PATCH="0"
VERSION="$MAJOR.$MINOR.$PATCH"
