#!/bin/sh -e

cd sbase.git

patch -p1 < ../install-add-GNU-s-extension.patch

# Lacks printf support
sed -i 's|find\\|\\|g' Makefile
# Much slower than GNU grep
sed -i 's|grep\\|\\|g' Makefile
# Lacks -i flag (how ironic!)
sed -i 's|sed\\|\\|g' Makefile
# Redundant
sed -i 's|xargs\\|\\|g' Makefile
# Redundant
sed -i 's|tar\\|\\|g' Makefile
# Redundant
sed -i 's|strings\\|\\|g' Makefile

make \
	PREFIX=/usr \
	CFLAGS="$CFLAGS -static" \
	LDFLAGS="$LDFLAGS -static"

make \
	PREFIX=/usr \
	CFLAGS="$CFLAGS -static" \
	LDFLAGS="$LDFLAGS -static" \
	DESTDIR="$DESTDIR" \
	install

install -Dm755 ../cron.run       "$DESTDIR/etc/sv/cron/run"
ln -sf /run/runit/supervise.cron "$DESTDIR/etc/sv/cron/supervise"

# used to be done automatically by the makefile

mv "$DESTDIR/usr/bin/xinstall"              "$DESTDIR/usr/bin/install"
mv "$DESTDIR/usr/share/man/man1/xinstall.1" "$DESTDIR/usr/share/man/man1/install.1"

find "$DESTDIR/usr/bin" -type f -exec strip --strip-unneeded {} \;

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > sbase@$VERSION.tar.gz
exit
