#!/bin/sh -e

gzip -cd libdisplay-info-$VERSION.tar.gz | tar -x
cd libdisplay-info-$VERSION

meson setup \
	-Dprefix=/usr \
	-Dbuildtype=release \
	-Ddefault_library=both \
	build

meson -C build compile
meson -C build install -d "$DESTDIR"

find "$DESTDIR/usr/lib" -type f -name '*.a'   -exec strip --strip-unneeded {} \;
find "$DESTDIR/usr/lib" -type f -name '*.so*' -exec strip --strip-unneeded {} \;
find "$DESTDIR/usr/bin" -type f -exec strip --strip-unneeded {} \;

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > libdisplay-info@$VERSION.tar.gz
exit
