#!/bin/sh -e

PRETTY_NAME=libdisplay-info
MAJOR=0
MINOR=1
PATCH=1
VERSION=0.1.1

mkdir temporary-builddir
DESTDIR="$PWD/temporary-builddir"

curl --location --remote-name --skip-existing https://gitlab.freedesktop.org/emersion/libdisplay-info/-/archive//libdisplay-info-$VERSION.tar.gz

gzip -cd libdisplay-info-$VERSION.tar.gz | tar -x
cd libdisplay-info-$VERSION

meson setup \
	-Dprefix=/usr \
	-Dbuildtype=release \
	-Ddefault_library=both \
	build

meson -C build compile
meson -C build install -d "$DESTDIR"

find "$DESTDIR/usr/lib" -type f -name '*.a'   -exec strip --strip-unneeded {} \;
find "$DESTDIR/usr/lib" -type f -name '*.so*' -exec strip --strip-unneeded {} \;
find "$DESTDIR/usr/bin" -type f -exec strip --strip-unneeded {} \;

su
chown -R root:root $DESTDIR
tar -zcC $DESTDIR . | gzip > ../libdisplay-info@$VERSION.tar.gz
exit
