#!/bin/sh -e

tar -xf make-$VERSION.tar.gz
cd make-$VERSION

./configure --prefix=/usr

make
make DESTDIR="$DESTDIR" install-strip

rm -rf "$DESTDIR/usr/share/info"
rm -rf "$DESTDIR/usr/share/locale"
