#!/bin/sh -e

tar -xf make-$VERSION.tar.gz
cd make-$VERSION

export LDFLAGS="$LDFLAGS -static"

./configure \
	--prefix=/usr \
	--disable-nls \
	--without-guile

make
make DESTDIR="$DESTDIR" install-strip

rm -rf "$DESTDIR/usr/share/info"
