#!/bin/sh -e

gzip -cd v$VERSION.tar.gz | tar -x

install -Dm644 -t "$DESTDIR/usr/share/lua" lua-luaepnf-$VERSION/src/epnf.lua

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > lua-epnf@$VERSION.tar.gz
exit
