#!/bin/sh -e

DEPENDENCIES="lua"
INFO=""
PRETTY_NAME="lpeg"
SOURCES="http://www.inf.puc-rio.br/~roberto/lpeg/lpeg-$VERSION.tar.gz"
SOURCES="$SOURCES patches/both-static-and-dynamic.patch"
MAJOR="1"
MINOR="1"
PATCH="0"
VERSION="$MAJOR.$MINOR.$PATCH"
