#!/bin/sh -e

gzip -cd libressl-$VERSION.tar.gz | tar -x
cd libressl-$VERSION

./configure \
	--prefix=/usr \
	--enable-static \
	--disable-tests

make
make DESTDIR="$DESTDIR" install-strip

rm -rf "$DESTDIR/usr/share/man"
find $DESTDIR -type f -name '*.la' -delete

install -Dm644 COPYING "$DESTDIR/usr/share/LICENSES/libressl.license"

su
chown -R root:root $DESTDIR
cd $DESTDIR
tar -c * | gzip > ../libressl@$VERSION.tar.gz
exit
