#!/bin/sh -e

PRETTY_NAME=libressl
MAJOR=4
MINOR=0
PATCH=0
VERSION=4.0.0

mkdir temporary-builddir
DESTDIR="$PWD/temporary-builddir"

curl --location --remote-name --skip-existing https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-$VERSION.tar.gz

gzip -cd libressl-$VERSION.tar.gz | tar -x
cd libressl-$VERSION

./configure \
	--prefix=/usr \
	--enable-static \
	--disable-tests

make
make DESTDIR=$DESTDIR install-strip

rm -rf "$DESTDIR/usr/share/man"
# rm -rf "$DESTDIR/usr/etc"
find $DESTDIR -type f -name '*.la' -delete

install -Dm644 COPYING "$DESTDIR/usr/share/LICENSES/libressl.license"

doas chown -R root:root $DESTDIR
doas sh -c "tar -zcC $DESTDIR . | gzip > ../libressl@$VERSION.tar.gz"
