#!/bin/sh -e

DEPENDENCIES=""
INFO="Free version of the TLS/crypto stack forked from OpenSSL"
PRETTY_NAME="libressl"
SOURCES="https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-$VERSION.tar.gz"
MAJOR="3"
MINOR="8"
PATCH="1"
VERSION="$MAJOR.$MINOR.$PATCH"
