#!/bin/sh -e

DEPENDENCIES=""
INFO="Free version of the TLS/crypto stack forked from OpenSSL"
PRETTY_NAME="libressl"
SOURCES="https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-$VERSION.tar.gz"
MAJOR="4"
MINOR="0"
PATCH="0"
VERSION="$MAJOR.$MINOR.$PATCH"
