#!/bin/sh -e

tar -xf grep-$VERSION.tar.xz
cd grep-$VERSION

export CFLAGS="$CFLAGS -Wno-error"

./configure --prefix=/usr

make
make DESTDIR="$DESTDIR" install-strip

rm -rf "$DESTDIR/usr/share/info"

ln -sf grep "$DESTDIR/usr/bin/ggrep"
