#!/bin/sh -e

tar -xf grep-$VERSION.tar.xz
cd grep-$VERSION

export CFLAGS="$CFLAGS -Wno-error -static"

./configure \
	--prefix=/usr \
	--disable-nls \
	--enable-threads=posix \
	--without-packager

make
make DESTDIR="$DESTDIR" install-strip

rm -rf "$DESTDIR/usr/share/info"

ln -sf grep "$DESTDIR/usr/bin/ggrep"
