#!/bin/sh -e

tar -xf grep-$VERSION.tar.xz
cd grep-$VERSION

export CFLAGS="$CFLAGS -Wno-error"

./configure --prefix=/usr

make
make DESTDIR="$DESTDIR" install

rm -rf "$DESTDIR/usr/share/info"

cp -f src/grep "$DESTDIR/usr/bin/ggrep"
