#!/bin/sh -e

gzip -cd Hack-v$VERSION-ttf.tar.gz | tar -x

mkdir -p "$DESTDIR/usr/share/fonts/TTF"
cp ttf/*.ttf "$DESTDIR/usr/share/fonts/TTF"

su
chown -R root:root $DESTDIR
cd $DESTDIR
tar -c * | gzip > ../ttf-hack@$VERSION.tar.gz
exit
